-- Seed Culture / Inventions : inventions majeures, figures associees et reperes techniques.
-- Cette migration ajoute uniquement du contenu read-only dans les tables Culture existantes.
-- Elle est idempotente et ne modifie pas le schema.
-- La categorie technique utilisee est volontairement "inventions", conformement a culture_items_category_check.

with source_items as (
	select *
	from (
	values
		('invention_dates', 'Roue', 'Antiquite', 'Mésopotamie', 'La roue est associée aux transports, aux poteries et aux mécanismes dès l’Antiquité.', 'forward', 'general', 'À quel usage associer la roue dans les premiers repères techniques ?', 'Transport et mécanismes', 'forward', 'period', 'À quelle période associer les premiers usages de la roue ?', 'Antiquité', 80000),
		('invention_dates', 'Écriture cunéiforme', 'Vers 3300 av. J.-C.', 'Mésopotamie', 'L’écriture cunéiforme est un système ancien utilisé pour compter, administrer et transmettre des informations.', 'forward', 'general', 'À quoi sert d’abord l’écriture cunéiforme ?', 'Compter et administrer', 'forward', 'period', 'À quelle période associer l’écriture cunéiforme ?', 'Vers 3300 av. J.-C.', 80001),
		('invention_dates', 'Papyrus', 'Antiquité', 'Égypte', 'Le papyrus est un support d’écriture fabriqué à partir d’une plante du Nil.', 'forward', 'general', 'Quel support d’écriture associer à l’Égypte antique ?', 'Papyrus', 'forward', 'period', 'À quelle période associer le papyrus comme support d’écriture ?', 'Antiquité', 80002),
		('invention_dates', 'Béton romain', 'Antiquité', 'Rome antique', 'Le béton romain permet de construire des ouvrages solides et durables dans l’Antiquité.', 'forward', 'general', 'Quel matériau de construction associer aux ouvrages durables de Rome antique ?', 'Béton romain', 'forward', 'period', 'À quelle période associer le béton romain ?', 'Antiquité', 80003),
		('invention_dates', 'Aqueduc', 'Antiquité', 'Monde romain', 'L’aqueduc permet de transporter l’eau vers les villes sur de longues distances.', 'forward', 'general', 'Quel ouvrage transporte l’eau vers les villes sur de longues distances ?', 'Aqueduc', 'forward', 'period', 'À quelle période associer les grands aqueducs romains ?', 'Antiquité', 80004),
		('invention_dates', 'Papier', 'IIe siècle', 'Chine', 'Le papier est souvent associé à Cai Lun et à la Chine des Han.', 'forward', 'person', 'Quelle figure est souvent associée à la diffusion ancienne du papier en Chine ?', 'Cai Lun', 'forward', 'period', 'À quelle période associer le papier attribué à Cai Lun ?', 'IIe siècle', 80005),
		('invention_dates', 'Boussole', 'Antiquité chinoise', 'Chine', 'La boussole est liée à l’usage de l’aimantation puis à la navigation.', 'forward', 'general', 'Quel instrument utilise l’aimantation pour indiquer une direction ?', 'Boussole', 'forward', 'period', 'À quelle aire culturelle associer les premiers usages de la boussole ?', 'Chine ancienne', 80006),
		('invention_dates', 'Poudre à canon', 'IXe siècle', 'Chine', 'La poudre à canon apparaît en Chine avant de se diffuser dans d’autres régions.', 'forward', 'general', 'Quelle invention chinoise est associée aux premiers explosifs militaires ?', 'Poudre à canon', 'forward', 'period', 'À quelle période associer les premières formes de poudre à canon ?', 'IXe siècle', 80007),
		('invention_dates', 'Porcelaine', 'Moyen Âge', 'Chine', 'La porcelaine chinoise est un repère important de l’histoire des techniques céramiques.', 'forward', 'general', 'Quelle céramique fine associer à la Chine impériale ?', 'Porcelaine', 'forward', 'period', 'À quelle période large associer la diffusion de la porcelaine chinoise ?', 'Moyen Âge', 80008),
		('invention_dates', 'Astrolabe', 'Antiquité et monde médiéval', 'Méditerranée', 'L’astrolabe sert à mesurer la position des astres et à aider l’orientation.', 'forward', 'general', 'Quel instrument sert à mesurer la position des astres ?', 'Astrolabe', 'forward', 'period', 'À quelles périodes associer l’astrolabe ?', 'Antiquité et monde médiéval', 80009),
		('invention_dates', 'Moulin à vent', 'Moyen Âge', 'Europe et Moyen-Orient', 'Le moulin à vent transforme l’énergie du vent en force mécanique.', 'forward', 'general', 'Quel dispositif transforme le vent en force mécanique ?', 'Moulin à vent', 'forward', 'period', 'À quelle période associer la diffusion des moulins à vent en Europe ?', 'Moyen Âge', 80010),
		('invention_dates', 'Lunettes correctrices', 'XIIIe siècle', 'Italie', 'Les lunettes correctrices améliorent la vision et se diffusent en Europe à partir du Moyen Âge.', 'forward', 'general', 'Quelle invention médiévale améliore la vision ?', 'Lunettes correctrices', 'forward', 'period', 'À quelle période associer les premières lunettes correctrices européennes ?', 'XIIIe siècle', 80011),
		('invention_dates', 'Horloge mécanique', 'XIIIe-XIVe siècles', 'Europe', 'L’horloge mécanique permet une mesure collective et régulière du temps.', 'forward', 'general', 'Quelle invention médiévale permet une mesure mécanique du temps ?', 'Horloge mécanique', 'forward', 'period', 'À quelle période associer les premières horloges mécaniques européennes ?', 'XIIIe-XIVe siècles', 80012),
		('invention_dates', 'Caractères mobiles en métal', 'XIe siècle', 'Chine', 'Bi Sheng est associé aux caractères mobiles en Chine, avant d’autres développements en Asie et en Europe.', 'forward', 'person', 'Quelle figure chinoise est associée aux caractères mobiles en argile ou en métal ?', 'Bi Sheng', 'forward', 'period', 'À quelle période associer Bi Sheng et les caractères mobiles ?', 'XIe siècle', 80013),
		('invention_dates', 'Imprimerie à caractères mobiles', 'XVe siècle', 'Europe', 'Johannes Gutenberg est associé à l’imprimerie à caractères mobiles en Europe.', 'forward', 'person', 'Quelle figure associer à l’imprimerie à caractères mobiles en Europe ?', 'Johannes Gutenberg', 'forward', 'period', 'À quelle période associer l’imprimerie de Gutenberg ?', 'XVe siècle', 80014),
		('invention_dates', 'Caravelle', 'XVe siècle', 'Europe atlantique', 'La caravelle est un navire associé aux voyages maritimes de la fin du Moyen Âge.', 'forward', 'general', 'Quel type de navire associer aux voyages atlantiques du XVe siècle ?', 'Caravelle', 'forward', 'period', 'À quelle période associer la caravelle ?', 'XVe siècle', 80015),
		('invention_dates', 'Télescope astronomique', 'Début du XVIIe siècle', 'Europe', 'Galilée contribue à l’usage astronomique du télescope au début du XVIIe siècle.', 'forward', 'person', 'Quelle figure associer à l’usage astronomique du télescope ?', 'Galilée', 'forward', 'period', 'À quelle période associer les premières observations au télescope de Galilée ?', 'Début du XVIIe siècle', 80016),
		('invention_dates', 'Microscope composé', 'XVIIe siècle', 'Europe', 'Le microscope composé permet d’observer des détails invisibles à l’œil nu.', 'forward', 'general', 'Quel instrument permet d’observer des détails invisibles à l’œil nu ?', 'Microscope composé', 'forward', 'period', 'À quelle période associer les premiers microscopes composés ?', 'XVIIe siècle', 80017),
		('invention_dates', 'Baromètre', '1643', 'Italie', 'Evangelista Torricelli est associé au baromètre à mercure.', 'forward', 'person', 'Quelle figure associer au baromètre à mercure ?', 'Evangelista Torricelli', 'forward', 'period', 'En quelle année associer l’expérience fondatrice du baromètre de Torricelli ?', '1643', 80018),
		('invention_dates', 'Machine à calculer de Pascal', '1642', 'France', 'Blaise Pascal conçoit une machine mécanique pour faciliter les calculs.', 'forward', 'person', 'Quelle figure associer à la Pascaline ?', 'Blaise Pascal', 'forward', 'period', 'À quelle période associer la machine à calculer de Pascal ?', 'XVIIe siècle', 80019),
		('invention_dates', 'Chronomètre de marine', 'XVIIIe siècle', 'Royaume-Uni', 'John Harrison développe des chronomètres utiles à la navigation maritime.', 'forward', 'person', 'Quelle figure associer au chronomètre de marine ?', 'John Harrison', 'forward', 'period', 'À quelle période associer les chronomètres de marine de John Harrison ?', 'XVIIIe siècle', 80020),
		('invention_dates', 'Métier à tisser Jacquard', '1801', 'France', 'Le métier Jacquard utilise des cartes perforées pour contrôler le tissage.', 'forward', 'person', 'Quelle figure associer au métier à tisser Jacquard ?', 'Joseph Marie Jacquard', 'forward', 'period', 'En quelle année associer la présentation du métier Jacquard ?', '1801', 80021),
		('invention_dates', 'Machine à vapeur perfectionnée', 'XVIIIe siècle', 'Royaume-Uni', 'James Watt améliore la machine à vapeur et contribue à son usage industriel.', 'forward', 'person', 'Quelle figure associer aux améliorations de la machine à vapeur ?', 'James Watt', 'forward', 'period', 'À quelle période associer les améliorations de la machine à vapeur par Watt ?', 'XVIIIe siècle', 80022),
		('invention_dates', 'Vaccination antivariolique', '1796', 'Royaume-Uni', 'Edward Jenner est associé à la vaccination contre la variole.', 'forward', 'person', 'Quelle figure associer à la vaccination antivariolique ?', 'Edward Jenner', 'forward', 'period', 'En quelle année associer l’expérience de Jenner sur la vaccination ?', '1796', 80023),
		('invention_dates', 'Pile électrique', '1800', 'Italie', 'Alessandro Volta met au point une pile capable de fournir un courant électrique continu.', 'forward', 'person', 'Quelle figure associer à la pile électrique ?', 'Alessandro Volta', 'forward', 'period', 'En quelle année associer la pile de Volta ?', '1800', 80024),
		('invention_dates', 'Locomotive à vapeur', 'Début du XIXe siècle', 'Royaume-Uni', 'La locomotive à vapeur transforme les transports terrestres au XIXe siècle.', 'forward', 'general', 'Quelle invention transforme les transports ferroviaires au XIXe siècle ?', 'Locomotive à vapeur', 'forward', 'period', 'À quelle période associer les premières locomotives à vapeur efficaces ?', 'Début du XIXe siècle', 80025),
		('invention_dates', 'Stéthoscope', '1816', 'France', 'René Laennec est associé à l’invention du stéthoscope.', 'forward', 'person', 'Quelle figure associer au stéthoscope ?', 'René Laennec', 'forward', 'period', 'En quelle année associer le stéthoscope de Laennec ?', '1816', 80026),
		('invention_dates', 'Photographie durable', 'XIXe siècle', 'France', 'Nicéphore Niépce est associé aux premiers procédés photographiques durables.', 'forward', 'person', 'Quelle figure associer aux premiers procédés photographiques durables ?', 'Nicéphore Niépce', 'forward', 'period', 'À quelle période associer les débuts de la photographie durable ?', 'XIXe siècle', 80027),
		('invention_dates', 'Daguerréotype', '1839', 'France', 'Louis Daguerre est associé au daguerréotype, l’un des premiers procédés photographiques diffusés.', 'forward', 'person', 'Quelle figure associer au daguerréotype ?', 'Louis Daguerre', 'forward', 'period', 'En quelle année associer l’annonce publique du daguerréotype ?', '1839', 80028),
		('invention_dates', 'Télégraphe électrique', 'XIXe siècle', 'États-Unis et Europe', 'Samuel Morse est associé au télégraphe électrique et au code Morse.', 'forward', 'person', 'Quelle figure associer au télégraphe électrique et au code Morse ?', 'Samuel Morse', 'forward', 'period', 'À quelle période associer le télégraphe électrique ?', 'XIXe siècle', 80029),
		('invention_dates', 'Anesthésie chirurgicale', '1846', 'États-Unis', 'L’usage public de l’éther comme anesthésique marque une étape importante de la chirurgie.', 'forward', 'general', 'Quelle innovation médicale rend possible une chirurgie moins douloureuse ?', 'Anesthésie chirurgicale', 'forward', 'period', 'En quelle année associer la démonstration publique de l’anesthésie à l’éther ?', '1846', 80030),
		('invention_dates', 'Acier Bessemer', '1856', 'Royaume-Uni', 'Le procédé Bessemer rend la production d’acier plus rapide et plus économique.', 'forward', 'person', 'Quelle figure associer au procédé Bessemer pour l’acier ?', 'Henry Bessemer', 'forward', 'period', 'En quelle année associer le procédé Bessemer ?', '1856', 80031),
		('invention_dates', 'Pasteurisation', 'XIXe siècle', 'France', 'Louis Pasteur est associé à la pasteurisation et à la microbiologie appliquée.', 'forward', 'person', 'Quelle figure associer à la pasteurisation ?', 'Louis Pasteur', 'forward', 'period', 'À quelle période associer la pasteurisation ?', 'XIXe siècle', 80032),
		('invention_dates', 'Dynamite', '1867', 'Suède', 'Alfred Nobel est associé à la dynamite, qui stabilise l’usage de la nitroglycérine.', 'forward', 'person', 'Quelle figure associer à la dynamite ?', 'Alfred Nobel', 'forward', 'period', 'En quelle année associer le brevet de la dynamite ?', '1867', 80033),
		('invention_dates', 'Machine à écrire', 'XIXe siècle', 'États-Unis', 'La machine à écrire transforme la production de documents au bureau.', 'forward', 'general', 'Quelle invention transforme la production de documents au bureau ?', 'Machine à écrire', 'forward', 'period', 'À quelle période associer la diffusion de la machine à écrire ?', 'XIXe siècle', 80034),
		('invention_dates', 'Téléphone', '1876', 'États-Unis', 'Alexander Graham Bell est souvent associé au téléphone, dans un contexte d’inventions concurrentes.', 'forward', 'person', 'Quelle figure est souvent associée au brevet du téléphone en 1876 ?', 'Alexander Graham Bell', 'forward', 'period', 'En quelle année associer le brevet du téléphone de Bell ?', '1876', 80035),
		('invention_dates', 'Phonographe', '1877', 'États-Unis', 'Thomas Edison est associé au phonographe, qui enregistre et restitue le son.', 'forward', 'person', 'Quelle figure associer au phonographe ?', 'Thomas Edison', 'forward', 'period', 'En quelle année associer le phonographe d’Edison ?', '1877', 80036),
		('invention_dates', 'Ampoule électrique pratique', 'Fin du XIXe siècle', 'États-Unis et Royaume-Uni', 'L’ampoule électrique pratique résulte de plusieurs améliorations, souvent associées à Edison et Swan.', 'forward', 'person', 'Quelles figures associer aux premières ampoules électriques pratiques ?', 'Thomas Edison et Joseph Swan', 'forward', 'period', 'À quelle période associer l’ampoule électrique pratique ?', 'Fin du XIXe siècle', 80037),
		('invention_dates', 'Moteur à combustion interne', 'XIXe siècle', 'Europe', 'Le moteur à combustion interne transforme les transports et l’industrie.', 'forward', 'general', 'Quel type de moteur transforme les transports modernes ?', 'Moteur à combustion interne', 'forward', 'period', 'À quelle période associer les premiers moteurs à combustion interne efficaces ?', 'XIXe siècle', 80038),
		('invention_dates', 'Automobile moderne', '1886', 'Allemagne', 'Karl Benz est associé à l’automobile à moteur à essence brevetée en 1886.', 'forward', 'person', 'Quelle figure associer à l’automobile à essence brevetée en 1886 ?', 'Karl Benz', 'forward', 'period', 'En quelle année associer le brevet automobile de Karl Benz ?', '1886', 80039),
		('invention_dates', 'Pneumatique démontable', '1891', 'France', 'Édouard et André Michelin contribuent au pneumatique démontable pour le vélo et l’automobile.', 'forward', 'person', 'Quelles figures associer au pneumatique démontable Michelin ?', 'Édouard et André Michelin', 'forward', 'period', 'En quelle année associer le pneumatique démontable Michelin ?', '1891', 80040),
		('invention_dates', 'Cinématographe', '1895', 'France', 'Les frères Lumière sont associés au cinématographe et aux premières projections publiques.', 'forward', 'person', 'Quelles figures associer au cinématographe Lumière ?', 'Auguste et Louis Lumière', 'forward', 'period', 'En quelle année associer les premières projections publiques du cinématographe Lumière ?', '1895', 80041),
		('invention_dates', 'Rayons X', '1895', 'Allemagne', 'Wilhelm Röntgen découvre les rayons X, rapidement utilisés en imagerie médicale.', 'forward', 'person', 'Quelle figure associer à la découverte des rayons X ?', 'Wilhelm Röntgen', 'forward', 'period', 'En quelle année associer la découverte des rayons X ?', '1895', 80042),
		('invention_dates', 'Radioactivité', '1896-1898', 'France', 'Henri Becquerel puis Marie et Pierre Curie sont associés aux débuts de la radioactivité.', 'forward', 'person', 'Quelles figures associer aux débuts de la radioactivité ?', 'Henri Becquerel et les Curie', 'forward', 'period', 'À quelle période associer les débuts de la radioactivité ?', '1896-1898', 80043),
		('invention_dates', 'Radio sans fil', 'Fin du XIXe siècle', 'Europe', 'Guglielmo Marconi est souvent associé au développement de la radio sans fil.', 'forward', 'person', 'Quelle figure est souvent associée à la radio sans fil ?', 'Guglielmo Marconi', 'forward', 'period', 'À quelle période associer les débuts de la radio sans fil ?', 'Fin du XIXe siècle', 80044),
		('invention_dates', 'Avion motorisé', '1903', 'États-Unis', 'Les frères Wright sont associés au premier vol motorisé contrôlé et soutenu.', 'forward', 'person', 'Quelles figures associer au premier vol motorisé contrôlé et soutenu ?', 'Les frères Wright', 'forward', 'period', 'En quelle année associer le vol des frères Wright ?', '1903', 80045),
		('invention_dates', 'Chaîne de montage automobile', 'Début du XXe siècle', 'États-Unis', 'Henry Ford popularise la chaîne de montage dans l’industrie automobile.', 'forward', 'person', 'Quelle figure associer à la chaîne de montage automobile popularisée aux États-Unis ?', 'Henry Ford', 'forward', 'period', 'À quelle période associer la chaîne de montage automobile de Ford ?', 'Début du XXe siècle', 80046),
		('invention_dates', 'Aspirine industrielle', '1899', 'Allemagne', 'L’aspirine est commercialisée à grande échelle à la fin du XIXe siècle.', 'forward', 'general', 'Quel médicament est commercialisé à grande échelle par Bayer en 1899 ?', 'Aspirine', 'forward', 'period', 'En quelle année associer la commercialisation de l’aspirine par Bayer ?', '1899', 80047),
		('invention_dates', 'Bakélite', '1907', 'États-Unis', 'Leo Baekeland est associé à la bakélite, un des premiers plastiques synthétiques.', 'forward', 'person', 'Quelle figure associer à la bakélite ?', 'Leo Baekeland', 'forward', 'period', 'En quelle année associer la bakélite ?', '1907', 80048),
		('invention_dates', 'Acier inoxydable', '1913', 'Royaume-Uni', 'Harry Brearley est souvent associé à l’acier inoxydable moderne.', 'forward', 'person', 'Quelle figure est souvent associée à l’acier inoxydable moderne ?', 'Harry Brearley', 'forward', 'period', 'En quelle année associer l’acier inoxydable de Brearley ?', '1913', 80049),
		('invention_dates', 'Réfrigérateur domestique', 'Début du XXe siècle', 'États-Unis et Europe', 'Le réfrigérateur domestique transforme la conservation des aliments.', 'forward', 'general', 'Quelle invention transforme la conservation quotidienne des aliments ?', 'Réfrigérateur domestique', 'forward', 'period', 'À quelle période associer la diffusion du réfrigérateur domestique ?', 'Début du XXe siècle', 80050),
		('invention_dates', 'Machine à laver électrique', 'Début du XXe siècle', 'États-Unis et Europe', 'La machine à laver électrique transforme une tâche domestique très répétitive.', 'forward', 'general', 'Quelle invention transforme le lavage du linge au foyer ?', 'Machine à laver électrique', 'forward', 'period', 'À quelle période associer la diffusion des machines à laver électriques ?', 'Début du XXe siècle', 80051),
		('invention_dates', 'Télévision électronique', 'Années 1920', 'États-Unis et Royaume-Uni', 'Philo Farnsworth et John Logie Baird sont associés aux débuts de la télévision.', 'forward', 'person', 'Quelles figures associer aux débuts de la télévision électronique ?', 'Philo Farnsworth et John Logie Baird', 'forward', 'period', 'À quelle période associer les débuts de la télévision électronique ?', 'Années 1920', 80052),
		('invention_dates', 'Pénicilline', '1928', 'Royaume-Uni', 'Alexander Fleming découvre la pénicilline, ensuite développée comme antibiotique.', 'forward', 'person', 'Quelle figure associer à la découverte de la pénicilline ?', 'Alexander Fleming', 'forward', 'period', 'En quelle année associer la découverte de la pénicilline ?', '1928', 80053),
		('invention_dates', 'Rasoir électrique', 'Années 1930', 'États-Unis', 'Le rasoir électrique illustre l’électrification des objets de soin personnel.', 'forward', 'general', 'Quel objet de soin personnel illustre l’électrification des usages quotidiens ?', 'Rasoir électrique', 'forward', 'period', 'À quelle période associer la diffusion du rasoir électrique ?', 'Années 1930', 80054),
		('invention_dates', 'Nylon', '1935', 'États-Unis', 'Wallace Carothers et DuPont sont associés au nylon, une fibre synthétique majeure.', 'forward', 'person', 'Quelle figure associer au nylon chez DuPont ?', 'Wallace Carothers', 'forward', 'period', 'En quelle année associer la mise au point du nylon ?', '1935', 80055),
		('invention_dates', 'Radar', 'Années 1930', 'Royaume-Uni et États-Unis', 'Le radar utilise les ondes radio pour détecter des objets à distance.', 'forward', 'general', 'Quelle technologie utilise les ondes radio pour détecter des objets à distance ?', 'Radar', 'forward', 'period', 'À quelle période associer le développement du radar moderne ?', 'Années 1930', 80056),
		('invention_dates', 'Moteur à réaction', 'Années 1930-1940', 'Royaume-Uni et Allemagne', 'Frank Whittle et Hans von Ohain sont associés aux premiers moteurs à réaction pratiques.', 'forward', 'person', 'Quelles figures associer aux premiers moteurs à réaction pratiques ?', 'Frank Whittle et Hans von Ohain', 'forward', 'period', 'À quelle période associer les premiers moteurs à réaction pratiques ?', 'Années 1930-1940', 80057),
		('invention_dates', 'Photocopieur', '1938', 'États-Unis', 'Chester Carlson est associé à la xérographie, à l’origine du photocopieur.', 'forward', 'person', 'Quelle figure associer à la xérographie du photocopieur ?', 'Chester Carlson', 'forward', 'period', 'En quelle année associer l’invention de la xérographie ?', '1938', 80058),
		('invention_dates', 'Ordinateur électronique', 'Années 1940', 'Royaume-Uni et États-Unis', 'Les premiers ordinateurs électroniques résultent de plusieurs équipes et besoins de calcul.', 'forward', 'general', 'À quelle technologie associer ENIAC et Colossus ?', 'Ordinateur électronique', 'forward', 'period', 'À quelle période associer les premiers ordinateurs électroniques ?', 'Années 1940', 80059),
		('invention_dates', 'Four à micro-ondes', 'Années 1940', 'États-Unis', 'Percy Spencer est associé à l’usage des micro-ondes pour chauffer les aliments.', 'forward', 'person', 'Quelle figure associer au four à micro-ondes ?', 'Percy Spencer', 'forward', 'period', 'À quelle période associer le four à micro-ondes ?', 'Années 1940', 80060),
		('invention_dates', 'Transistor', '1947', 'États-Unis', 'Le transistor est mis au point aux Bell Labs par Bardeen, Brattain et Shockley.', 'forward', 'person', 'Quelles figures associer au transistor des Bell Labs ?', 'Bardeen, Brattain et Shockley', 'forward', 'period', 'En quelle année associer le transistor des Bell Labs ?', '1947', 80061),
		('invention_dates', 'Carte bancaire', 'Milieu du XXe siècle', 'États-Unis', 'La carte bancaire transforme les paiements en les détachant progressivement de l’argent liquide.', 'forward', 'general', 'Quelle innovation transforme les paiements sans argent liquide immédiat ?', 'Carte bancaire', 'forward', 'period', 'À quelle période associer les premières cartes bancaires modernes ?', 'Milieu du XXe siècle', 80062),
		('invention_dates', 'Code-barres', '1952', 'États-Unis', 'Norman Joseph Woodland et Bernard Silver sont associés au brevet du code-barres.', 'forward', 'person', 'Quelles figures associer au brevet du code-barres ?', 'Norman Joseph Woodland et Bernard Silver', 'forward', 'period', 'En quelle année associer le brevet du code-barres ?', '1952', 80063),
		('invention_dates', 'Pilule contraceptive', 'Années 1950-1960', 'États-Unis', 'La pilule contraceptive résulte de travaux scientifiques, médicaux et sociaux autour de la contraception hormonale.', 'forward', 'general', 'Quelle innovation médicale transforme la contraception hormonale ?', 'Pilule contraceptive', 'forward', 'period', 'À quelle période associer la diffusion de la pilule contraceptive ?', 'Années 1950-1960', 80064),
		('invention_dates', 'Circuit intégré', '1958-1959', 'États-Unis', 'Jack Kilby et Robert Noyce sont associés aux premiers circuits intégrés.', 'forward', 'person', 'Quelles figures associer aux premiers circuits intégrés ?', 'Jack Kilby et Robert Noyce', 'forward', 'period', 'À quelle période associer les premiers circuits intégrés ?', '1958-1959', 80065),
		('invention_dates', 'Laser', '1960', 'États-Unis', 'Theodore Maiman réalise le premier laser fonctionnel en 1960.', 'forward', 'person', 'Quelle figure associer au premier laser fonctionnel ?', 'Theodore Maiman', 'forward', 'period', 'En quelle année associer le premier laser fonctionnel ?', '1960', 80066),
		('invention_dates', 'Satellite de télécommunications', 'Années 1960', 'International', 'Les satellites de télécommunications permettent des transmissions à grande distance.', 'forward', 'general', 'Quelle technologie permet des transmissions par relais spatial ?', 'Satellite de télécommunications', 'forward', 'period', 'À quelle période associer les premiers satellites de télécommunications ?', 'Années 1960', 80067),
		('invention_dates', 'Souris informatique', 'Années 1960', 'États-Unis', 'Douglas Engelbart est associé à la souris informatique et aux interfaces interactives.', 'forward', 'person', 'Quelle figure associer à la souris informatique ?', 'Douglas Engelbart', 'forward', 'period', 'À quelle période associer la souris informatique d’Engelbart ?', 'Années 1960', 80068),
		('invention_dates', 'ARPANET', '1969', 'États-Unis', 'ARPANET est un réseau précurseur important d’Internet.', 'forward', 'general', 'Quel réseau est un précurseur important d’Internet ?', 'ARPANET', 'forward', 'period', 'En quelle année associer la mise en service d’ARPANET ?', '1969', 80069),
		('invention_dates', 'Microprocesseur', '1971', 'États-Unis', 'Le microprocesseur concentre les fonctions de calcul d’un processeur sur une puce.', 'forward', 'general', 'Quelle invention concentre un processeur sur une puce ?', 'Microprocesseur', 'forward', 'period', 'En quelle année associer l’Intel 4004, premier microprocesseur commercial ?', '1971', 80070),
		('invention_dates', 'Tomodensitométrie', 'Années 1970', 'Royaume-Uni et États-Unis', 'Le scanner médical combine rayons X et calcul informatique pour produire des images du corps.', 'forward', 'general', 'Quelle imagerie médicale combine rayons X et calcul informatique ?', 'Tomodensitométrie', 'forward', 'period', 'À quelle période associer les premiers scanners médicaux ?', 'Années 1970', 80071),
		('invention_dates', 'Imagerie par résonance magnétique', 'Années 1970-1980', 'International', 'L’IRM utilise des propriétés magnétiques pour produire des images médicales.', 'forward', 'general', 'Quelle technique d’imagerie médicale utilise des propriétés magnétiques ?', 'IRM', 'forward', 'period', 'À quelle période associer les premières applications médicales de l’IRM ?', 'Années 1970-1980', 80072),
		('invention_dates', 'Fibre optique moderne', 'Années 1970', 'International', 'La fibre optique transmet des informations par la lumière sur de longues distances.', 'forward', 'general', 'Quelle technologie transmet des informations par la lumière ?', 'Fibre optique', 'forward', 'period', 'À quelle période associer la fibre optique moderne ?', 'Années 1970', 80073),
		('invention_dates', 'GPS', 'Années 1970-1990', 'États-Unis', 'Le GPS est un système de positionnement par satellites développé progressivement.', 'forward', 'general', 'Quel système permet le positionnement par satellites ?', 'GPS', 'forward', 'period', 'À quelle période associer le développement du GPS ?', 'Années 1970-1990', 80074),
		('invention_dates', 'Walkman', '1979', 'Japon', 'Le Walkman rend l’écoute musicale personnelle et portable très populaire.', 'forward', 'general', 'Quel appareil rend l’écoute musicale portable très populaire à partir de 1979 ?', 'Walkman', 'forward', 'period', 'En quelle année associer le lancement du Walkman ?', '1979', 80075),
		('invention_dates', 'Ordinateur personnel', 'Années 1970-1980', 'États-Unis', 'L’ordinateur personnel rend l’informatique plus accessible au bureau et au foyer.', 'forward', 'general', 'Quelle innovation rend l’informatique plus accessible au foyer ?', 'Ordinateur personnel', 'forward', 'period', 'À quelle période associer l’essor de l’ordinateur personnel ?', 'Années 1970-1980', 80076),
		('invention_dates', 'CD audio', '1982', 'Japon et Europe', 'Le disque compact audio diffuse la musique sous forme numérique.', 'forward', 'general', 'Quel support numérique remplace progressivement le disque vinyle dans les années 1980 ?', 'CD audio', 'forward', 'period', 'En quelle année associer le lancement commercial du CD audio ?', '1982', 80077),
		('invention_dates', 'World Wide Web', '1989-1991', 'Europe', 'Tim Berners-Lee est associé au World Wide Web, construit sur Internet.', 'forward', 'person', 'Quelle figure associer au World Wide Web ?', 'Tim Berners-Lee', 'forward', 'period', 'À quelle période associer la création du World Wide Web ?', '1989-1991', 80078),
		('invention_dates', 'Batterie lithium-ion', 'Années 1980-1990', 'International', 'La batterie lithium-ion devient essentielle aux appareils mobiles et aux véhicules électriques.', 'forward', 'general', 'Quelle batterie est essentielle aux appareils mobiles modernes ?', 'Batterie lithium-ion', 'forward', 'period', 'À quelle période associer la mise au point des batteries lithium-ion modernes ?', 'Années 1980-1990', 80079),
		('invention_dates', 'SMS', '1992', 'Europe', 'Le SMS popularise les messages courts sur téléphone mobile.', 'forward', 'general', 'Quelle technologie popularise les messages courts sur téléphone mobile ?', 'SMS', 'forward', 'period', 'En quelle année associer le premier SMS ?', '1992', 80080),
		('invention_dates', 'QR code', '1994', 'Japon', 'Le QR code est conçu pour stocker et lire rapidement des informations visuelles.', 'forward', 'general', 'Quel code visuel bidimensionnel est conçu au Japon en 1994 ?', 'QR code', 'forward', 'period', 'En quelle année associer le QR code ?', '1994', 80081),
		('invention_dates', 'Moteur de recherche Web', 'Années 1990', 'États-Unis', 'Les moteurs de recherche rendent le Web plus navigable en indexant les pages.', 'forward', 'general', 'Quelle technologie indexe les pages pour rendre le Web plus navigable ?', 'Moteur de recherche Web', 'forward', 'period', 'À quelle période associer l’essor des moteurs de recherche Web ?', 'Années 1990', 80082),
		('invention_dates', 'Wi-Fi', 'Années 1990', 'International', 'Le Wi-Fi permet des connexions réseau sans fil à courte portée.', 'forward', 'general', 'Quelle technologie permet des connexions réseau sans fil à courte portée ?', 'Wi-Fi', 'forward', 'period', 'À quelle période associer les premiers standards Wi-Fi ?', 'Années 1990', 80083),
		('invention_dates', 'MP3', 'Années 1990', 'Allemagne et international', 'Le MP3 compresse le son numérique et transforme la circulation de la musique.', 'forward', 'general', 'Quel format compresse le son numérique dans les années 1990 ?', 'MP3', 'forward', 'period', 'À quelle période associer la diffusion du MP3 ?', 'Années 1990', 80084),
		('invention_dates', 'Clé USB', 'Années 2000', 'International', 'La clé USB rend le stockage portable simple et réinscriptible.', 'forward', 'general', 'Quel objet rend le stockage numérique portable et réinscriptible ?', 'Clé USB', 'forward', 'period', 'À quelle période associer la diffusion de la clé USB ?', 'Années 2000', 80085),
		('invention_dates', 'Smartphone moderne', 'Années 2000', 'International', 'Le smartphone combine téléphone, Internet mobile, appareil photo et applications.', 'forward', 'general', 'Quel objet combine téléphone, Internet mobile, appareil photo et applications ?', 'Smartphone moderne', 'forward', 'period', 'À quelle période associer l’essor du smartphone moderne ?', 'Années 2000', 80086),
		('invention_dates', 'Écran tactile capacitif', 'Années 2000', 'International', 'L’écran tactile capacitif facilite les interfaces mobiles au doigt.', 'forward', 'general', 'Quelle technologie facilite les interfaces mobiles au doigt ?', 'Écran tactile capacitif', 'forward', 'period', 'À quelle période associer la diffusion des écrans tactiles capacitifs modernes ?', 'Années 2000', 80087),
		('invention_dates', 'Impression 3D', 'Années 1980-2000', 'International', 'L’impression 3D fabrique des objets couche par couche à partir d’un modèle numérique.', 'forward', 'general', 'Quelle technique fabrique des objets couche par couche ?', 'Impression 3D', 'forward', 'period', 'À quelle période associer les débuts puis la diffusion de l’impression 3D ?', 'Années 1980-2000', 80088),
		('invention_dates', 'Séquençage de l’ADN', 'Années 1970-2000', 'International', 'Le séquençage de l’ADN permet de lire l’ordre des bases génétiques.', 'forward', 'general', 'Quelle technique permet de lire l’ordre des bases de l’ADN ?', 'Séquençage de l’ADN', 'forward', 'period', 'À quelle période associer le développement du séquençage de l’ADN ?', 'Années 1970-2000', 80089),
		('invention_dates', 'CRISPR-Cas9', 'Années 2010', 'International', 'CRISPR-Cas9 est un outil d’édition génétique associé à plusieurs équipes scientifiques.', 'forward', 'general', 'Quel outil d’édition génétique est associé à CRISPR-Cas9 ?', 'Édition génétique', 'forward', 'period', 'À quelle période associer l’essor de CRISPR-Cas9 ?', 'Années 2010', 80090),
		('invention_dates', 'Panneau solaire photovoltaïque', 'XXe siècle', 'États-Unis et international', 'Le panneau photovoltaïque convertit la lumière en électricité.', 'forward', 'general', 'Quelle technologie convertit la lumière en électricité ?', 'Panneau solaire photovoltaïque', 'forward', 'period', 'À quelle période associer les cellules photovoltaïques modernes ?', 'XXe siècle', 80091),
		('invention_dates', 'Éolienne moderne', 'XXe siècle', 'International', 'L’éolienne moderne transforme l’énergie du vent en électricité.', 'forward', 'general', 'Quelle machine transforme le vent en électricité ?', 'Éolienne moderne', 'forward', 'period', 'À quelle période associer les éoliennes électriques modernes ?', 'XXe siècle', 80092),
		('invention_dates', 'Réacteur nucléaire civil', 'XXe siècle', 'International', 'Le réacteur nucléaire civil produit de l’électricité à partir de réactions nucléaires contrôlées.', 'forward', 'general', 'Quelle installation produit de l’électricité à partir de réactions nucléaires contrôlées ?', 'Réacteur nucléaire civil', 'forward', 'period', 'À quelle période associer les premiers réacteurs nucléaires civils ?', 'XXe siècle', 80093),
		('invention_dates', 'Dessalement par osmose inverse', 'XXe siècle', 'International', 'L’osmose inverse permet de retirer le sel de l’eau pour produire de l’eau douce.', 'forward', 'general', 'Quelle technique retire le sel de l’eau par membrane ?', 'Osmose inverse', 'forward', 'period', 'À quelle période associer le dessalement moderne par osmose inverse ?', 'XXe siècle', 80094),
		('invention_dates', 'LED', 'XXe siècle', 'International', 'La diode électroluminescente produit de la lumière avec un bon rendement énergétique.', 'forward', 'general', 'Quelle source lumineuse repose sur une diode électroluminescente ?', 'LED', 'forward', 'period', 'À quelle période associer le développement des LED modernes ?', 'XXe siècle', 80095),
		('invention_dates', 'Drone civil', 'XXIe siècle', 'International', 'Le drone civil rend accessibles des usages de prise de vue, mesure et surveillance à distance.', 'forward', 'general', 'Quel appareil volant sans pilote se diffuse pour des usages civils ?', 'Drone civil', 'forward', 'period', 'À quelle période associer la diffusion des drones civils ?', 'XXIe siècle', 80096),
		('invention_dates', 'Voiture électrique moderne', 'XXIe siècle', 'International', 'La voiture électrique moderne se diffuse avec les progrès des batteries et de l’électronique.', 'forward', 'general', 'Quel véhicule se diffuse avec les progrès des batteries lithium-ion ?', 'Voiture électrique moderne', 'forward', 'period', 'À quelle période associer l’essor de la voiture électrique moderne ?', 'XXIe siècle', 80097),
		('invention_dates', 'Assistant vocal', 'XXIe siècle', 'International', 'L’assistant vocal combine reconnaissance de la parole, logiciels et services connectés.', 'forward', 'general', 'Quelle technologie répond à des commandes parlées dans des services connectés ?', 'Assistant vocal', 'forward', 'period', 'À quelle période associer la diffusion des assistants vocaux ?', 'XXIe siècle', 80098),
		('invention_dates', 'Vaccin à ARN messager', 'XXIe siècle', 'International', 'Les vaccins à ARN messager résultent de plusieurs décennies de recherche et d’applications récentes.', 'forward', 'general', 'Quelle technologie vaccinale utilise un ARN messager ?', 'Vaccin à ARN messager', 'forward', 'period', 'À quelle période associer les premières grandes applications des vaccins à ARN messager ?', 'XXIe siècle', 80099),
		('invention_people', 'Archimède', 'Antiquité', 'Monde grec', 'Archimède est associé à des machines simples, à la poussée et à des travaux de mécanique.', 'reverse', 'general', 'Quel domaine technique associer à Archimède ?', 'Mécanique', null, null, null, null, 81000),
		('invention_people', 'Héron d’Alexandrie', 'Antiquité', 'Égypte hellénistique', 'Héron d’Alexandrie est associé à des automates et à l’éolipyle.', 'reverse', 'general', 'Quelle machine expérimentale associer à Héron d’Alexandrie ?', 'Éolipyle', null, null, null, null, 81001),
		('invention_people', 'Cai Lun', 'IIe siècle', 'Chine', 'Cai Lun est souvent associé à l’amélioration et à la diffusion du papier en Chine.', 'reverse', 'general', 'Quelle invention associer à Cai Lun ?', 'Papier', null, null, null, null, 81002),
		('invention_people', 'Bi Sheng', 'XIe siècle', 'Chine', 'Bi Sheng est associé aux caractères mobiles en Chine.', 'reverse', 'general', 'Quelle technique associer à Bi Sheng ?', 'Caractères mobiles', null, null, null, null, 81003),
		('invention_people', 'Al-Jazari', 'XIIe-XIIIe siècles', 'Monde islamique', 'Al-Jazari est associé à des automates et à des dispositifs hydrauliques.', 'reverse', 'general', 'Quels dispositifs associer à Al-Jazari ?', 'Automates hydrauliques', null, null, null, null, 81004),
		('invention_people', 'Johannes Gutenberg', 'XVe siècle', 'Europe', 'Gutenberg est associé à l’imprimerie à caractères mobiles en Europe.', 'reverse', 'general', 'Quelle invention associer à Johannes Gutenberg ?', 'Imprimerie à caractères mobiles', null, null, null, null, 81005),
		('invention_people', 'Léonard de Vinci', 'Renaissance', 'Italie', 'Léonard de Vinci est associé à de nombreux dessins de machines et dispositifs techniques.', 'reverse', 'general', 'Quel type de travaux techniques associer à Léonard de Vinci ?', 'Dessins de machines', null, null, null, null, 81006),
		('invention_people', 'Galilée', 'Début du XVIIe siècle', 'Italie', 'Galilée contribue à l’usage astronomique du télescope.', 'reverse', 'general', 'Quel instrument scientifique associer à Galilée ?', 'Télescope astronomique', null, null, null, null, 81007),
		('invention_people', 'Evangelista Torricelli', 'XVIIe siècle', 'Italie', 'Torricelli est associé au baromètre à mercure.', 'reverse', 'general', 'Quel instrument associer à Evangelista Torricelli ?', 'Baromètre', null, null, null, null, 81008),
		('invention_people', 'Blaise Pascal', 'XVIIe siècle', 'France', 'Pascal conçoit une machine mécanique de calcul appelée Pascaline.', 'reverse', 'general', 'Quelle machine associer à Blaise Pascal ?', 'Pascaline', null, null, null, null, 81009),
		('invention_people', 'Christiaan Huygens', 'XVIIe siècle', 'Pays-Bas', 'Huygens est associé à l’horloge à pendule.', 'reverse', 'general', 'Quelle invention horlogère associer à Christiaan Huygens ?', 'Horloge à pendule', null, null, null, null, 81010),
		('invention_people', 'Antonie van Leeuwenhoek', 'XVIIe siècle', 'Pays-Bas', 'Leeuwenhoek est associé à l’observation microscopique de micro-organismes.', 'reverse', 'general', 'Quel instrument scientifique associer à Antonie van Leeuwenhoek ?', 'Microscope', null, null, null, null, 81011),
		('invention_people', 'Denis Papin', 'XVIIe siècle', 'France', 'Denis Papin est associé à la marmite à vapeur et à des recherches sur la vapeur.', 'reverse', 'general', 'Quelle technologie associer à Denis Papin ?', 'Vapeur sous pression', null, null, null, null, 81012),
		('invention_people', 'John Harrison', 'XVIIIe siècle', 'Royaume-Uni', 'John Harrison développe des chronomètres de marine.', 'reverse', 'general', 'Quelle invention associer à John Harrison ?', 'Chronomètre de marine', null, null, null, null, 81013),
		('invention_people', 'James Watt', 'XVIIIe siècle', 'Royaume-Uni', 'Watt améliore la machine à vapeur et contribue à son usage industriel.', 'reverse', 'general', 'Quelle machine associer à James Watt ?', 'Machine à vapeur', null, null, null, null, 81014),
		('invention_people', 'Edward Jenner', 'XVIIIe siècle', 'Royaume-Uni', 'Edward Jenner est associé à la vaccination antivariolique.', 'reverse', 'general', 'Quelle innovation médicale associer à Edward Jenner ?', 'Vaccination', null, null, null, null, 81015),
		('invention_people', 'Alessandro Volta', '1800', 'Italie', 'Volta est associé à la pile électrique.', 'reverse', 'general', 'Quelle invention associer à Alessandro Volta ?', 'Pile électrique', null, null, null, null, 81016),
		('invention_people', 'Joseph Marie Jacquard', '1801', 'France', 'Jacquard est associé au métier à tisser à cartes perforées.', 'reverse', 'general', 'Quelle machine associer à Joseph Marie Jacquard ?', 'Métier à tisser Jacquard', null, null, null, null, 81017),
		('invention_people', 'George Stephenson', 'XIXe siècle', 'Royaume-Uni', 'Stephenson est associé au développement de locomotives à vapeur efficaces.', 'reverse', 'general', 'Quel transport associer à George Stephenson ?', 'Locomotive à vapeur', null, null, null, null, 81018),
		('invention_people', 'René Laennec', '1816', 'France', 'Laennec est associé au stéthoscope.', 'reverse', 'general', 'Quel instrument médical associer à René Laennec ?', 'Stéthoscope', null, null, null, null, 81019),
		('invention_people', 'Nicéphore Niépce', 'XIXe siècle', 'France', 'Niépce est associé aux premiers procédés photographiques durables.', 'reverse', 'general', 'Quelle technique associer à Nicéphore Niépce ?', 'Photographie durable', null, null, null, null, 81020),
		('invention_people', 'Louis Daguerre', '1839', 'France', 'Daguerre est associé au daguerréotype.', 'reverse', 'general', 'Quel procédé photographique associer à Louis Daguerre ?', 'Daguerréotype', null, null, null, null, 81021),
		('invention_people', 'Ada Lovelace', 'XIXe siècle', 'Royaume-Uni', 'Ada Lovelace est associée aux premiers raisonnements sur les programmes de calcul.', 'reverse', 'general', 'Quel domaine associer à Ada Lovelace ?', 'Programmation', null, null, null, null, 81022),
		('invention_people', 'Charles Babbage', 'XIXe siècle', 'Royaume-Uni', 'Babbage conçoit des machines de calcul mécaniques.', 'reverse', 'general', 'Quelle machine associer à Charles Babbage ?', 'Machine analytique', null, null, null, null, 81023),
		('invention_people', 'Samuel Morse', 'XIXe siècle', 'États-Unis', 'Morse est associé au télégraphe électrique et à un code de transmission.', 'reverse', 'general', 'Quelle technologie associer à Samuel Morse ?', 'Télégraphe électrique', null, null, null, null, 81024),
		('invention_people', 'Louis Pasteur', 'XIXe siècle', 'France', 'Pasteur est associé à la pasteurisation et à la microbiologie appliquée.', 'reverse', 'general', 'Quel procédé associer à Louis Pasteur ?', 'Pasteurisation', null, null, null, null, 81025),
		('invention_people', 'Alfred Nobel', '1867', 'Suède', 'Nobel est associé à la dynamite.', 'reverse', 'general', 'Quelle invention associer à Alfred Nobel ?', 'Dynamite', null, null, null, null, 81026),
		('invention_people', 'Henry Bessemer', '1856', 'Royaume-Uni', 'Bessemer est associé à un procédé de production de l’acier.', 'reverse', 'general', 'Quel procédé associer à Henry Bessemer ?', 'Procédé Bessemer', null, null, null, null, 81027),
		('invention_people', 'Dmitri Mendeleïev', '1869', 'Russie', 'Mendeleïev est associé au tableau périodique des éléments.', 'reverse', 'general', 'Quel outil scientifique associer à Dmitri Mendeleïev ?', 'Tableau périodique', null, null, null, null, 81028),
		('invention_people', 'Alexander Graham Bell', '1876', 'États-Unis', 'Bell est souvent associé au téléphone dans un contexte d’inventions concurrentes.', 'reverse', 'general', 'Quelle invention associer à Alexander Graham Bell ?', 'Téléphone', null, null, null, null, 81029),
		('invention_people', 'Thomas Edison', 'XIXe siècle', 'États-Unis', 'Edison est associé au phonographe, à l’ampoule pratique et à l’électricité domestique.', 'reverse', 'general', 'Quelle invention sonore associer à Thomas Edison ?', 'Phonographe', null, null, null, null, 81030),
		('invention_people', 'Joseph Swan', 'XIXe siècle', 'Royaume-Uni', 'Swan est associé aux premières lampes électriques pratiques.', 'reverse', 'general', 'Quelle invention associer à Joseph Swan ?', 'Lampe électrique', null, null, null, null, 81031),
		('invention_people', 'Nikola Tesla', 'XIXe-XXe siècles', 'Europe et États-Unis', 'Tesla est associé au courant alternatif et à plusieurs systèmes électriques.', 'reverse', 'general', 'Quel domaine technique associer à Nikola Tesla ?', 'Courant alternatif', null, null, null, null, 81032),
		('invention_people', 'Karl Benz', '1886', 'Allemagne', 'Benz est associé à l’automobile à moteur à essence.', 'reverse', 'general', 'Quelle invention associer à Karl Benz ?', 'Automobile', null, null, null, null, 81033),
		('invention_people', 'Rudolf Diesel', '1890s', 'Allemagne', 'Diesel est associé au moteur qui porte son nom.', 'reverse', 'general', 'Quel moteur associer à Rudolf Diesel ?', 'Moteur Diesel', null, null, null, null, 81034),
		('invention_people', 'Guglielmo Marconi', 'Fin du XIXe siècle', 'Italie', 'Marconi est souvent associé au développement de la radio sans fil.', 'reverse', 'general', 'Quelle technologie associer à Guglielmo Marconi ?', 'Radio sans fil', null, null, null, null, 81035),
		('invention_people', 'Wilhelm Röntgen', '1895', 'Allemagne', 'Röntgen découvre les rayons X.', 'reverse', 'general', 'Quelle découverte associer à Wilhelm Röntgen ?', 'Rayons X', null, null, null, null, 81036),
		('invention_people', 'Marie Curie', 'XIXe-XXe siècles', 'France et Pologne', 'Marie Curie est associée aux recherches sur la radioactivité.', 'reverse', 'general', 'Quel domaine scientifique associer à Marie Curie ?', 'Radioactivité', null, null, null, null, 81037),
		('invention_people', 'Les frères Wright', '1903', 'États-Unis', 'Les frères Wright sont associés au premier vol motorisé contrôlé et soutenu.', 'reverse', 'general', 'Quelle invention associer aux frères Wright ?', 'Avion motorisé', null, null, null, null, 81038),
		('invention_people', 'Henry Ford', 'Début du XXe siècle', 'États-Unis', 'Ford popularise la chaîne de montage automobile.', 'reverse', 'general', 'Quelle méthode industrielle associer à Henry Ford ?', 'Chaîne de montage', null, null, null, null, 81039),
		('invention_people', 'Leo Baekeland', '1907', 'États-Unis', 'Baekeland est associé à la bakélite.', 'reverse', 'general', 'Quel matériau associer à Leo Baekeland ?', 'Bakélite', null, null, null, null, 81040),
		('invention_people', 'Harry Brearley', '1913', 'Royaume-Uni', 'Brearley est souvent associé à l’acier inoxydable moderne.', 'reverse', 'general', 'Quel matériau associer à Harry Brearley ?', 'Acier inoxydable', null, null, null, null, 81041),
		('invention_people', 'John Logie Baird', 'Années 1920', 'Royaume-Uni', 'Baird est associé aux débuts de la télévision.', 'reverse', 'general', 'Quelle technologie associer à John Logie Baird ?', 'Télévision', null, null, null, null, 81042),
		('invention_people', 'Philo Farnsworth', 'Années 1920', 'États-Unis', 'Farnsworth est associé aux débuts de la télévision électronique.', 'reverse', 'general', 'Quelle technologie associer à Philo Farnsworth ?', 'Télévision électronique', null, null, null, null, 81043),
		('invention_people', 'Alexander Fleming', '1928', 'Royaume-Uni', 'Fleming découvre la pénicilline.', 'reverse', 'general', 'Quelle découverte médicale associer à Alexander Fleming ?', 'Pénicilline', null, null, null, null, 81044),
		('invention_people', 'Alan Turing', 'XXe siècle', 'Royaume-Uni', 'Turing est associé aux fondements de l’informatique et au calcul théorique.', 'reverse', 'general', 'Quel domaine associer à Alan Turing ?', 'Calcul théorique', null, null, null, null, 81045),
		('invention_people', 'Grace Hopper', 'XXe siècle', 'États-Unis', 'Grace Hopper est associée aux langages de programmation et aux compilateurs.', 'reverse', 'general', 'Quel domaine associer à Grace Hopper ?', 'Langages de programmation', null, null, null, null, 81046),
		('invention_people', 'Hedy Lamarr', 'XXe siècle', 'États-Unis', 'Hedy Lamarr est associée à des travaux sur l’étalement de spectre en communication.', 'reverse', 'general', 'Quel domaine technique associer à Hedy Lamarr ?', 'Communication sans fil', null, null, null, null, 81047),
		('invention_people', 'Katherine Johnson', 'XXe siècle', 'États-Unis', 'Katherine Johnson est associée aux calculs de trajectoires spatiales à la NASA.', 'reverse', 'general', 'Quel domaine associer à Katherine Johnson ?', 'Calculs spatiaux', null, null, null, null, 81048),
		('invention_people', 'John Bardeen', '1947', 'États-Unis', 'Bardeen fait partie de l’équipe associée au transistor.', 'reverse', 'general', 'Quelle invention associer à John Bardeen ?', 'Transistor', null, null, null, null, 81049),
		('invention_people', 'William Shockley', '1947', 'États-Unis', 'Shockley fait partie de l’équipe associée au transistor.', 'reverse', 'general', 'Quelle invention associer à William Shockley ?', 'Transistor', null, null, null, null, 81050),
		('invention_people', 'Percy Spencer', 'Années 1940', 'États-Unis', 'Spencer est associé au four à micro-ondes.', 'reverse', 'general', 'Quelle invention associer à Percy Spencer ?', 'Four à micro-ondes', null, null, null, null, 81051),
		('invention_people', 'Chester Carlson', '1938', 'États-Unis', 'Carlson est associé à la xérographie.', 'reverse', 'general', 'Quelle technique associer à Chester Carlson ?', 'Xérographie', null, null, null, null, 81052),
		('invention_people', 'Jack Kilby', '1958', 'États-Unis', 'Kilby est associé aux premiers circuits intégrés.', 'reverse', 'general', 'Quelle invention associer à Jack Kilby ?', 'Circuit intégré', null, null, null, null, 81053),
		('invention_people', 'Robert Noyce', '1959', 'États-Unis', 'Noyce est associé aux premiers circuits intégrés.', 'reverse', 'general', 'Quelle invention associer à Robert Noyce ?', 'Circuit intégré', null, null, null, null, 81054),
		('invention_people', 'Theodore Maiman', '1960', 'États-Unis', 'Maiman réalise le premier laser fonctionnel.', 'reverse', 'general', 'Quelle invention associer à Theodore Maiman ?', 'Laser', null, null, null, null, 81055),
		('invention_people', 'Douglas Engelbart', 'Années 1960', 'États-Unis', 'Engelbart est associé à la souris informatique et aux interfaces interactives.', 'reverse', 'general', 'Quelle invention associer à Douglas Engelbart ?', 'Souris informatique', null, null, null, null, 81056),
		('invention_people', 'Vinton Cerf', 'Années 1970', 'États-Unis', 'Vinton Cerf est associé aux protocoles TCP/IP avec Robert Kahn.', 'reverse', 'general', 'Quel protocole associer à Vinton Cerf ?', 'TCP/IP', null, null, null, null, 81057),
		('invention_people', 'Robert Kahn', 'Années 1970', 'États-Unis', 'Robert Kahn est associé aux protocoles TCP/IP avec Vinton Cerf.', 'reverse', 'general', 'Quel protocole associer à Robert Kahn ?', 'TCP/IP', null, null, null, null, 81058),
		('invention_people', 'Tim Berners-Lee', '1989-1991', 'Royaume-Uni', 'Berners-Lee est associé au World Wide Web.', 'reverse', 'general', 'Quelle invention associer à Tim Berners-Lee ?', 'World Wide Web', null, null, null, null, 81059),
		('invention_people', 'Martin Cooper', 'Années 1970', 'États-Unis', 'Martin Cooper est associé aux premiers téléphones mobiles portables.', 'reverse', 'general', 'Quelle invention associer à Martin Cooper ?', 'Téléphone mobile portable', null, null, null, null, 81060),
		('invention_people', 'Norman Joseph Woodland', '1952', 'États-Unis', 'Woodland est associé au brevet du code-barres avec Bernard Silver.', 'reverse', 'general', 'Quelle invention associer à Norman Joseph Woodland ?', 'Code-barres', null, null, null, null, 81061),
		('invention_people', 'Bernard Silver', '1952', 'États-Unis', 'Silver est associé au brevet du code-barres avec Norman Joseph Woodland.', 'reverse', 'general', 'Quelle invention associer à Bernard Silver ?', 'Code-barres', null, null, null, null, 81062),
		('invention_people', 'Stephanie Kwolek', '1965', 'États-Unis', 'Kwolek est associée au Kevlar.', 'reverse', 'general', 'Quel matériau associer à Stephanie Kwolek ?', 'Kevlar', null, null, null, null, 81063),
		('invention_people', 'Gertrude Elion', 'XXe siècle', 'États-Unis', 'Gertrude Elion est associée à des médicaments importants en pharmacologie.', 'reverse', 'general', 'Quel domaine associer à Gertrude Elion ?', 'Pharmacologie', null, null, null, null, 81064),
		('invention_people', 'Rosalind Franklin', 'XXe siècle', 'Royaume-Uni', 'Franklin est associée à des images de diffraction utiles à la compréhension de l’ADN.', 'reverse', 'general', 'Quel domaine associer à Rosalind Franklin ?', 'Structure de l’ADN', null, null, null, null, 81065),
		('invention_people', 'Frederick Sanger', 'XXe siècle', 'Royaume-Uni', 'Sanger est associé à des méthodes de séquençage en biologie moléculaire.', 'reverse', 'general', 'Quelle technique associer à Frederick Sanger ?', 'Séquençage', null, null, null, null, 81066),
		('invention_people', 'Tu Youyou', 'XXe siècle', 'Chine', 'Tu Youyou est associée à l’artémisinine, utilisée contre le paludisme.', 'reverse', 'general', 'Quelle molécule médicale associer à Tu Youyou ?', 'Artémisinine', null, null, null, null, 81067),
		('invention_people', 'Katalin Karikó', 'XXIe siècle', 'Hongrie et États-Unis', 'Katalin Karikó est associée aux recherches sur l’ARN messager.', 'reverse', 'general', 'Quelle technologie biomédicale associer à Katalin Karikó ?', 'ARN messager', null, null, null, null, 81068),
		('invention_people', 'Drew Weissman', 'XXIe siècle', 'États-Unis', 'Drew Weissman est associé aux recherches sur l’ARN messager avec Katalin Karikó.', 'reverse', 'general', 'Quelle technologie biomédicale associer à Drew Weissman ?', 'ARN messager', null, null, null, null, 81069),
		('invention_people', 'Emmanuelle Charpentier', 'XXIe siècle', 'France', 'Charpentier est associée à CRISPR-Cas9 avec Jennifer Doudna.', 'reverse', 'general', 'Quelle technique associer à Emmanuelle Charpentier ?', 'CRISPR-Cas9', null, null, null, null, 81070),
		('invention_people', 'Jennifer Doudna', 'XXIe siècle', 'États-Unis', 'Doudna est associée à CRISPR-Cas9 avec Emmanuelle Charpentier.', 'reverse', 'general', 'Quelle technique associer à Jennifer Doudna ?', 'CRISPR-Cas9', null, null, null, null, 81071),
		('invention_people', 'Akira Yoshino', 'XXe siècle', 'Japon', 'Akira Yoshino est associé aux batteries lithium-ion modernes.', 'reverse', 'general', 'Quelle technologie associer à Akira Yoshino ?', 'Batterie lithium-ion', null, null, null, null, 81072),
		('invention_people', 'Shuji Nakamura', 'XXe siècle', 'Japon', 'Shuji Nakamura est associé aux LED bleues efficaces.', 'reverse', 'general', 'Quelle technologie associer à Shuji Nakamura ?', 'LED bleue', null, null, null, null, 81073),
		('invention_people', 'Nils Bohlin', '1959', 'Suède', 'Nils Bohlin est associé à la ceinture de sécurité trois points.', 'reverse', 'general', 'Quelle innovation de sécurité associer à Nils Bohlin ?', 'Ceinture de sécurité trois points', null, null, null, null, 81074),
		('invention_markers', 'Innovation incrémentale', 'Notion technique', 'International', 'Une innovation incrémentale améliore progressivement une technique existante.', 'standard', 'general', 'Quelle notion désigne une amélioration progressive d’une technique existante ?', 'Innovation incrémentale', 'forward', 'general', 'À quel type de changement associer l’innovation incrémentale ?', 'Amélioration progressive', 82000),
		('invention_markers', 'Rupture technologique', 'Notion technique', 'International', 'Une rupture technologique modifie fortement les usages ou les systèmes existants.', 'standard', 'general', 'Quelle notion désigne une innovation qui modifie fortement les usages existants ?', 'Rupture technologique', 'forward', 'general', 'À quel type de changement associer une rupture technologique ?', 'Changement majeur', 82001),
		('invention_markers', 'Diffusion technique', 'Notion historique', 'International', 'La diffusion technique désigne la propagation d’une innovation dans une société.', 'standard', 'general', 'Quelle notion désigne la propagation d’une innovation dans une société ?', 'Diffusion technique', 'forward', 'general', 'À quoi sert la notion de diffusion technique ?', 'Comprendre la propagation des innovations', 82002),
		('invention_markers', 'Brevet', 'Propriété industrielle', 'International', 'Le brevet protège temporairement une invention en échange de sa description publique.', 'standard', 'general', 'Quel titre protège temporairement une invention décrite publiquement ?', 'Brevet', 'forward', 'general', 'À quel domaine associer le brevet ?', 'Propriété industrielle', 82003),
		('invention_markers', 'Prototype', 'Conception', 'International', 'Un prototype est une première version testable d’un objet ou d’un système.', 'standard', 'general', 'Quelle première version testable précède souvent une production plus large ?', 'Prototype', 'forward', 'general', 'À quelle étape associer un prototype ?', 'Conception', 82004),
		('invention_markers', 'Standard technique', 'Normalisation', 'International', 'Un standard technique facilite la compatibilité entre objets, réseaux ou services.', 'standard', 'general', 'Quelle notion facilite la compatibilité entre objets, réseaux ou services ?', 'Standard technique', 'forward', 'general', 'À quel domaine associer un standard technique ?', 'Normalisation', 82005),
		('invention_markers', 'Interopérabilité', 'Systèmes techniques', 'International', 'L’interopérabilité permet à des systèmes différents de fonctionner ensemble.', 'standard', 'general', 'Quelle capacité permet à des systèmes différents de fonctionner ensemble ?', 'Interopérabilité', 'forward', 'general', 'À quel enjeu associer l’interopérabilité ?', 'Compatibilité des systèmes', 82006),
		('invention_markers', 'Énergie mécanique', 'Physique appliquée', 'International', 'L’énergie mécanique est liée au mouvement et aux forces dans les machines.', 'standard', 'general', 'Quelle énergie est liée au mouvement et aux forces dans les machines ?', 'Énergie mécanique', 'forward', 'general', 'À quel domaine associer l’énergie mécanique ?', 'Physique appliquée', 82007),
		('invention_markers', 'Énergie thermique', 'Physique appliquée', 'International', 'L’énergie thermique est liée à la chaleur et aux échanges de température.', 'standard', 'general', 'Quelle énergie est liée à la chaleur et aux échanges de température ?', 'Énergie thermique', 'forward', 'general', 'À quel domaine associer l’énergie thermique ?', 'Physique appliquée', 82008),
		('invention_markers', 'Électricité', 'Science appliquée', 'International', 'L’électricité devient un support central de l’énergie, de l’éclairage et des communications.', 'standard', 'general', 'Quelle forme d’énergie devient centrale pour l’éclairage et les communications ?', 'Électricité', 'forward', 'general', 'À quel domaine associer l’électricité dans les techniques modernes ?', 'Énergie et communication', 82009),
		('invention_markers', 'Électromagnétisme', 'XIXe siècle', 'Europe', 'L’électromagnétisme relie phénomènes électriques et magnétiques dans une théorie commune.', 'standard', 'general', 'Quel domaine relie phénomènes électriques et magnétiques ?', 'Électromagnétisme', 'forward', 'period', 'À quelle période associer la formulation classique de l’électromagnétisme ?', 'XIXe siècle', 82010),
		('invention_markers', 'Microbiologie', 'XIXe siècle', 'Europe', 'La microbiologie étudie les micro-organismes et transforme médecine, hygiène et alimentation.', 'standard', 'general', 'Quelle discipline étudie les micro-organismes ?', 'Microbiologie', 'forward', 'period', 'À quelle période associer l’essor de la microbiologie moderne ?', 'XIXe siècle', 82011),
		('invention_markers', 'Hygiène hospitalière', 'XIXe siècle', 'Europe', 'L’hygiène hospitalière se développe avec la compréhension des infections et de leur prévention.', 'standard', 'general', 'Quelle pratique vise à limiter les infections dans les soins ?', 'Hygiène hospitalière', 'forward', 'period', 'À quelle période associer l’essor de l’hygiène hospitalière moderne ?', 'XIXe siècle', 82012),
		('invention_markers', 'Révolution industrielle', 'XVIIIe-XIXe siècles', 'Europe', 'La révolution industrielle transforme production, énergie, transports et organisation du travail.', 'standard', 'general', 'Quel processus transforme production, énergie et transports aux XVIIIe-XIXe siècles ?', 'Révolution industrielle', 'forward', 'period', 'À quelle période associer la révolution industrielle ?', 'XVIIIe-XIXe siècles', 82013),
		('invention_markers', 'Mécanisation', 'Révolution industrielle', 'International', 'La mécanisation remplace ou complète le travail manuel par des machines.', 'standard', 'general', 'Quelle notion désigne le remplacement ou complément du travail manuel par des machines ?', 'Mécanisation', 'forward', 'general', 'À quel grand processus associer la mécanisation ?', 'Révolution industrielle', 82014),
		('invention_markers', 'Production de masse', 'XXe siècle', 'International', 'La production de masse organise la fabrication en grandes séries standardisées.', 'standard', 'general', 'Quelle organisation produit des biens en grandes séries standardisées ?', 'Production de masse', 'forward', 'period', 'À quelle période associer l’essor de la production de masse ?', 'XXe siècle', 82015),
		('invention_markers', 'Taylorisme', 'Début du XXe siècle', 'États-Unis', 'Le taylorisme organise scientifiquement les tâches dans le travail industriel.', 'standard', 'general', 'Quelle méthode organise scientifiquement les tâches du travail industriel ?', 'Taylorisme', 'forward', 'period', 'À quelle période associer le taylorisme ?', 'Début du XXe siècle', 82016),
		('invention_markers', 'Fordisme', 'Début du XXe siècle', 'États-Unis', 'Le fordisme combine production de masse, chaîne de montage et salaires plus élevés.', 'standard', 'general', 'Quelle organisation industrielle associer à la chaîne de montage automobile ?', 'Fordisme', 'forward', 'period', 'À quelle période associer le fordisme ?', 'Début du XXe siècle', 82017),
		('invention_markers', 'Électrification', 'XIXe-XXe siècles', 'International', 'L’électrification diffuse l’électricité dans les villes, les usines et les foyers.', 'standard', 'general', 'Quelle transformation diffuse l’électricité dans les villes, usines et foyers ?', 'Électrification', 'forward', 'period', 'À quelle période associer l’électrification massive ?', 'XIXe-XXe siècles', 82018),
		('invention_markers', 'Assainissement urbain', 'XIXe siècle', 'Europe', 'L’assainissement urbain améliore l’eau, les égouts et la santé publique.', 'standard', 'general', 'Quelle transformation urbaine améliore l’eau, les égouts et la santé publique ?', 'Assainissement urbain', 'forward', 'period', 'À quelle période associer l’essor de l’assainissement urbain moderne ?', 'XIXe siècle', 82019),
		('invention_markers', 'Chaîne du froid', 'XXe siècle', 'International', 'La chaîne du froid maintient des produits à basse température pendant transport et stockage.', 'standard', 'general', 'Quelle organisation maintient des produits à basse température du transport au stockage ?', 'Chaîne du froid', 'forward', 'period', 'À quelle période associer la diffusion moderne de la chaîne du froid ?', 'XXe siècle', 82020),
		('invention_markers', 'Moteur thermique', 'XIXe siècle', 'Europe', 'Le moteur thermique transforme l’énergie d’un combustible en travail mécanique.', 'standard', 'general', 'Quel moteur transforme l’énergie d’un combustible en travail mécanique ?', 'Moteur thermique', 'forward', 'period', 'À quelle période associer l’essor des moteurs thermiques modernes ?', 'XIXe siècle', 82021),
		('invention_markers', 'Courant alternatif', 'Fin du XIXe siècle', 'International', 'Le courant alternatif facilite le transport de l’électricité sur de longues distances.', 'standard', 'general', 'Quel type de courant facilite le transport de l’électricité sur de longues distances ?', 'Courant alternatif', 'forward', 'period', 'À quelle période associer l’essor du courant alternatif industriel ?', 'Fin du XIXe siècle', 82022),
		('invention_markers', 'Télécommunication', 'XIXe-XXe siècles', 'International', 'Les télécommunications transmettent des informations à distance par signaux techniques.', 'standard', 'general', 'Quel domaine transmet des informations à distance par signaux techniques ?', 'Télécommunication', 'forward', 'period', 'À quelle période associer l’essor des télécommunications modernes ?', 'XIXe-XXe siècles', 82023),
		('invention_markers', 'Onde radio', 'XIXe-XXe siècles', 'International', 'Les ondes radio permettent des transmissions sans fil.', 'standard', 'general', 'Quel type d’onde permet des transmissions sans fil ?', 'Onde radio', 'forward', 'period', 'À quelle période associer les premières applications des ondes radio ?', 'XIXe-XXe siècles', 82024),
		('invention_markers', 'Semi-conducteur', 'XXe siècle', 'International', 'Les semi-conducteurs sont essentiels aux transistors, puces et circuits électroniques.', 'standard', 'general', 'Quel matériau est essentiel aux transistors et aux puces électroniques ?', 'Semi-conducteur', 'forward', 'period', 'À quelle période associer l’essor des semi-conducteurs modernes ?', 'XXe siècle', 82025),
		('invention_markers', 'Miniaturisation', 'XXe siècle', 'International', 'La miniaturisation réduit la taille des composants tout en augmentant leurs performances.', 'standard', 'general', 'Quelle tendance réduit la taille des composants tout en augmentant leurs performances ?', 'Miniaturisation', 'forward', 'period', 'À quelle période associer la miniaturisation électronique ?', 'XXe siècle', 82026),
		('invention_markers', 'Informatique', 'XXe siècle', 'International', 'L’informatique traite automatiquement l’information grâce à des machines et des programmes.', 'standard', 'general', 'Quel domaine traite automatiquement l’information avec des machines et programmes ?', 'Informatique', 'forward', 'period', 'À quelle période associer l’essor de l’informatique moderne ?', 'XXe siècle', 82027),
		('invention_markers', 'Algorithme', 'Notion ancienne et informatique moderne', 'International', 'Un algorithme est une suite d’instructions pour résoudre un problème.', 'standard', 'general', 'Quelle notion désigne une suite d’instructions pour résoudre un problème ?', 'Algorithme', 'forward', 'general', 'À quoi sert un algorithme ?', 'Résoudre un problème étape par étape', 82028),
		('invention_markers', 'Programme informatique', 'XXe siècle', 'International', 'Un programme informatique décrit des instructions exécutables par une machine.', 'standard', 'general', 'Quelle notion désigne des instructions exécutables par une machine ?', 'Programme informatique', 'forward', 'period', 'À quelle période associer l’essor des programmes informatiques modernes ?', 'XXe siècle', 82029),
		('invention_markers', 'Réseau informatique', 'XXe siècle', 'International', 'Un réseau informatique relie des machines pour échanger des données.', 'standard', 'general', 'Quelle structure relie des machines pour échanger des données ?', 'Réseau informatique', 'forward', 'period', 'À quelle période associer l’essor des réseaux informatiques ?', 'XXe siècle', 82030),
		('invention_markers', 'Protocole TCP/IP', 'Années 1970-1980', 'États-Unis', 'TCP/IP définit des règles essentielles pour l’échange de données sur Internet.', 'standard', 'general', 'Quel protocole est essentiel à l’échange de données sur Internet ?', 'TCP/IP', 'forward', 'period', 'À quelle période associer la mise en place de TCP/IP ?', 'Années 1970-1980', 82031),
		('invention_markers', 'Hypertexte', 'XXe siècle', 'International', 'L’hypertexte relie des documents par des liens consultables.', 'standard', 'general', 'Quelle notion relie des documents par des liens consultables ?', 'Hypertexte', 'forward', 'period', 'À quelle période associer l’hypertexte moderne ?', 'XXe siècle', 82032),
		('invention_markers', 'Interface graphique', 'Années 1970-1980', 'États-Unis', 'L’interface graphique facilite l’usage des ordinateurs avec fenêtres, icônes et souris.', 'standard', 'general', 'Quelle interface facilite l’usage des ordinateurs avec fenêtres et icônes ?', 'Interface graphique', 'forward', 'period', 'À quelle période associer les interfaces graphiques modernes ?', 'Années 1970-1980', 82033),
		('invention_markers', 'Logiciel libre', 'Années 1980', 'International', 'Le logiciel libre donne aux utilisateurs des libertés d’usage, d’étude, de modification et de partage.', 'standard', 'general', 'Quelle notion donne des libertés d’usage, d’étude, de modification et de partage du logiciel ?', 'Logiciel libre', 'forward', 'period', 'À quelle période associer le mouvement du logiciel libre ?', 'Années 1980', 82034),
		('invention_markers', 'Open source', 'Années 1990', 'International', 'L’open source met l’accent sur l’accès au code source et la collaboration.', 'standard', 'general', 'Quelle notion met l’accent sur l’accès au code source et la collaboration ?', 'Open source', 'forward', 'period', 'À quelle période associer le terme open source ?', 'Années 1990', 82035),
		('invention_markers', 'Cryptographie', 'Antiquité et numérique moderne', 'International', 'La cryptographie protège des messages ou des données par des méthodes de chiffrement.', 'standard', 'general', 'Quelle discipline protège des messages ou données par chiffrement ?', 'Cryptographie', 'forward', 'general', 'À quoi sert la cryptographie ?', 'Protéger des informations', 82036),
		('invention_markers', 'Intelligence artificielle', 'XXe-XXIe siècles', 'International', 'L’intelligence artificielle regroupe des méthodes permettant à des machines d’effectuer certaines tâches cognitives.', 'standard', 'general', 'Quel domaine permet à des machines d’effectuer certaines tâches cognitives ?', 'Intelligence artificielle', 'forward', 'period', 'À quelle période associer l’essor de l’intelligence artificielle moderne ?', 'XXe-XXIe siècles', 82037),
		('invention_markers', 'Apprentissage automatique', 'XXe-XXIe siècles', 'International', 'L’apprentissage automatique permet à des systèmes d’améliorer leurs résultats à partir de données.', 'standard', 'general', 'Quelle méthode permet à un système d’améliorer ses résultats à partir de données ?', 'Apprentissage automatique', 'forward', 'period', 'À quelle période associer l’apprentissage automatique moderne ?', 'XXe-XXIe siècles', 82038),
		('invention_markers', 'Robotique', 'XXe-XXIe siècles', 'International', 'La robotique conçoit des machines capables d’effectuer des actions physiques programmées ou autonomes.', 'standard', 'general', 'Quel domaine conçoit des machines capables d’actions physiques programmées ou autonomes ?', 'Robotique', 'forward', 'period', 'À quelle période associer l’essor de la robotique moderne ?', 'XXe-XXIe siècles', 82039),
		('invention_markers', 'Biotechnologie', 'XXe-XXIe siècles', 'International', 'La biotechnologie utilise le vivant ou ses composants pour produire des biens, soins ou procédés.', 'standard', 'general', 'Quel domaine utilise le vivant ou ses composants pour produire des biens ou soins ?', 'Biotechnologie', 'forward', 'period', 'À quelle période associer l’essor des biotechnologies modernes ?', 'XXe-XXIe siècles', 82040),
		('invention_markers', 'Génie génétique', 'XXe-XXIe siècles', 'International', 'Le génie génétique modifie ou analyse le matériel génétique avec des outils biologiques.', 'standard', 'general', 'Quel domaine modifie ou analyse le matériel génétique avec des outils biologiques ?', 'Génie génétique', 'forward', 'period', 'À quelle période associer l’essor du génie génétique moderne ?', 'XXe-XXIe siècles', 82041),
		('invention_markers', 'Thérapie génique', 'XXe-XXIe siècles', 'International', 'La thérapie génique cherche à traiter une maladie en agissant sur le matériel génétique.', 'standard', 'general', 'Quelle approche médicale agit sur le matériel génétique pour traiter une maladie ?', 'Thérapie génique', 'forward', 'period', 'À quelle période associer les premières thérapies géniques modernes ?', 'XXe-XXIe siècles', 82042),
		('invention_markers', 'Antibiotique', 'XXe siècle', 'International', 'Un antibiotique agit contre des bactéries et transforme le traitement de nombreuses infections.', 'standard', 'general', 'Quel type de médicament agit contre des bactéries ?', 'Antibiotique', 'forward', 'period', 'À quelle période associer l’essor des antibiotiques modernes ?', 'XXe siècle', 82043),
		('invention_markers', 'Vaccination', 'XVIIIe-XXIe siècles', 'International', 'La vaccination stimule le système immunitaire contre une maladie donnée.', 'standard', 'general', 'Quelle pratique stimule le système immunitaire contre une maladie donnée ?', 'Vaccination', 'forward', 'period', 'À quelle période associer les débuts de la vaccination moderne ?', 'XVIIIe siècle', 82044),
		('invention_markers', 'Imagerie médicale', 'XXe siècle', 'International', 'L’imagerie médicale permet d’observer l’intérieur du corps sans chirurgie directe.', 'standard', 'general', 'Quel domaine permet d’observer l’intérieur du corps sans chirurgie directe ?', 'Imagerie médicale', 'forward', 'period', 'À quelle période associer l’essor de l’imagerie médicale moderne ?', 'XXe siècle', 82045),
		('invention_markers', 'Prothèse moderne', 'XXe-XXIe siècles', 'International', 'La prothèse moderne remplace ou assiste une partie du corps avec des matériaux et mécanismes avancés.', 'standard', 'general', 'Quel dispositif remplace ou assiste une partie du corps ?', 'Prothèse', 'forward', 'period', 'À quelle période associer les prothèses modernes avancées ?', 'XXe-XXIe siècles', 82046),
		('invention_markers', 'Dialyse', 'XXe siècle', 'International', 'La dialyse remplace partiellement la fonction de filtration des reins.', 'standard', 'general', 'Quelle technique remplace partiellement la filtration des reins ?', 'Dialyse', 'forward', 'period', 'À quelle période associer l’essor de la dialyse moderne ?', 'XXe siècle', 82047),
		('invention_markers', 'Pacemaker', 'XXe siècle', 'International', 'Le pacemaker aide à réguler le rythme cardiaque.', 'standard', 'general', 'Quel dispositif aide à réguler le rythme cardiaque ?', 'Pacemaker', 'forward', 'period', 'À quelle période associer les pacemakers modernes ?', 'XXe siècle', 82048),
		('invention_markers', 'Énergie renouvelable', 'XXe-XXIe siècles', 'International', 'Les énergies renouvelables reposent sur des ressources qui se reconstituent naturellement.', 'standard', 'general', 'Quelle notion regroupe les sources d’énergie qui se reconstituent naturellement ?', 'Énergie renouvelable', 'forward', 'period', 'À quelle période associer l’essor contemporain des énergies renouvelables ?', 'XXe-XXIe siècles', 82049),
		('invention_markers', 'Stockage d’énergie', 'XXe-XXIe siècles', 'International', 'Le stockage d’énergie permet de conserver de l’électricité ou de la chaleur pour un usage ultérieur.', 'standard', 'general', 'Quelle fonction permet de conserver de l’électricité ou de la chaleur pour plus tard ?', 'Stockage d’énergie', 'forward', 'period', 'À quelle période associer l’essor du stockage d’énergie moderne ?', 'XXe-XXIe siècles', 82050),
		('invention_markers', 'Réseau électrique', 'XIXe-XXe siècles', 'International', 'Le réseau électrique relie production, transport et distribution d’électricité.', 'standard', 'general', 'Quelle infrastructure relie production, transport et distribution d’électricité ?', 'Réseau électrique', 'forward', 'period', 'À quelle période associer l’essor des réseaux électriques modernes ?', 'XIXe-XXe siècles', 82051),
		('invention_markers', 'Pile à combustible', 'XIXe-XXIe siècles', 'International', 'La pile à combustible produit de l’électricité à partir d’une réaction électrochimique.', 'standard', 'general', 'Quel dispositif produit de l’électricité par réaction électrochimique ?', 'Pile à combustible', 'forward', 'period', 'À quelle période associer la pile à combustible ?', 'XIXe-XXIe siècles', 82052),
		('invention_markers', 'Moteur électrique', 'XIXe siècle', 'International', 'Le moteur électrique transforme l’énergie électrique en mouvement mécanique.', 'standard', 'general', 'Quel moteur transforme l’électricité en mouvement mécanique ?', 'Moteur électrique', 'forward', 'period', 'À quelle période associer l’essor des moteurs électriques ?', 'XIXe siècle', 82053),
		('invention_markers', 'Transport ferroviaire', 'XIXe siècle', 'Europe et Amérique du Nord', 'Le chemin de fer transforme les déplacements et le transport de marchandises.', 'standard', 'general', 'Quel mode de transport transforme les déplacements terrestres au XIXe siècle ?', 'Chemin de fer', 'forward', 'period', 'À quelle période associer l’essor du transport ferroviaire ?', 'XIXe siècle', 82054),
		('invention_markers', 'Aviation', 'XXe siècle', 'International', 'L’aviation développe le transport aérien motorisé et transforme les distances.', 'standard', 'general', 'Quel domaine développe le transport aérien motorisé ?', 'Aviation', 'forward', 'period', 'À quelle période associer l’essor de l’aviation motorisée ?', 'XXe siècle', 82055),
		('invention_markers', 'Conquête spatiale', 'XXe siècle', 'International', 'La conquête spatiale regroupe lanceurs, satellites, vols habités et exploration robotique.', 'standard', 'general', 'Quel domaine regroupe lanceurs, satellites, vols habités et exploration robotique ?', 'Conquête spatiale', 'forward', 'period', 'À quelle période associer l’essor de la conquête spatiale ?', 'XXe siècle', 82056),
		('invention_markers', 'Satellites artificiels', 'XXe siècle', 'International', 'Les satellites artificiels servent à l’observation, aux communications et à la navigation.', 'standard', 'general', 'Quels objets orbitaux servent à l’observation, aux communications et à la navigation ?', 'Satellites artificiels', 'forward', 'period', 'À quelle période associer les premiers satellites artificiels ?', 'XXe siècle', 82057),
		('invention_markers', 'Géolocalisation', 'XXe-XXIe siècles', 'International', 'La géolocalisation permet de déterminer une position grâce à des signaux ou données.', 'standard', 'general', 'Quelle fonction permet de déterminer une position grâce à des signaux ou données ?', 'Géolocalisation', 'forward', 'period', 'À quelle période associer la géolocalisation moderne ?', 'XXe-XXIe siècles', 82058),
		('invention_markers', 'Capteur', 'XXe-XXIe siècles', 'International', 'Un capteur mesure une grandeur physique ou chimique pour la transformer en information.', 'standard', 'general', 'Quel composant mesure une grandeur pour la transformer en information ?', 'Capteur', 'forward', 'period', 'À quelle période associer l’essor des capteurs électroniques modernes ?', 'XXe-XXIe siècles', 82059),
		('invention_markers', 'Internet des objets', 'XXIe siècle', 'International', 'L’Internet des objets relie des objets physiques à des réseaux numériques.', 'standard', 'general', 'Quelle notion relie des objets physiques à des réseaux numériques ?', 'Internet des objets', 'forward', 'period', 'À quelle période associer l’Internet des objets ?', 'XXIe siècle', 82060),
		('invention_markers', 'Cloud computing', 'XXIe siècle', 'International', 'Le cloud computing fournit des ressources informatiques à distance via le réseau.', 'standard', 'general', 'Quelle notion fournit des ressources informatiques à distance via le réseau ?', 'Cloud computing', 'forward', 'period', 'À quelle période associer l’essor du cloud computing ?', 'XXIe siècle', 82061),
		('invention_markers', 'Blockchain', 'XXIe siècle', 'International', 'La blockchain organise un registre distribué partagé entre plusieurs acteurs.', 'standard', 'general', 'Quelle technologie organise un registre distribué partagé ?', 'Blockchain', 'forward', 'period', 'À quelle période associer l’essor de la blockchain ?', 'XXIe siècle', 82062),
		('invention_markers', 'Réalité virtuelle', 'XXe-XXIe siècles', 'International', 'La réalité virtuelle plonge l’utilisateur dans un environnement simulé.', 'standard', 'general', 'Quelle technologie plonge l’utilisateur dans un environnement simulé ?', 'Réalité virtuelle', 'forward', 'period', 'À quelle période associer l’essor de la réalité virtuelle moderne ?', 'XXe-XXIe siècles', 82063),
		('invention_markers', 'Réalité augmentée', 'XXe-XXIe siècles', 'International', 'La réalité augmentée superpose des informations numériques au monde réel.', 'standard', 'general', 'Quelle technologie superpose des informations numériques au monde réel ?', 'Réalité augmentée', 'forward', 'period', 'À quelle période associer l’essor de la réalité augmentée ?', 'XXe-XXIe siècles', 82064),
		('invention_markers', 'Nanotechnologie', 'XXe-XXIe siècles', 'International', 'La nanotechnologie travaille la matière à l’échelle du nanomètre.', 'standard', 'general', 'Quel domaine travaille la matière à l’échelle du nanomètre ?', 'Nanotechnologie', 'forward', 'period', 'À quelle période associer l’essor des nanotechnologies ?', 'XXe-XXIe siècles', 82065),
		('invention_markers', 'Matériau composite', 'XXe-XXIe siècles', 'International', 'Un matériau composite combine plusieurs matériaux pour obtenir des propriétés spécifiques.', 'standard', 'general', 'Quel type de matériau combine plusieurs matériaux pour obtenir des propriétés spécifiques ?', 'Matériau composite', 'forward', 'period', 'À quelle période associer l’essor des matériaux composites modernes ?', 'XXe-XXIe siècles', 82066),
		('invention_markers', 'Béton armé', 'XIXe-XXe siècles', 'Europe', 'Le béton armé combine béton et acier pour renforcer les constructions.', 'standard', 'general', 'Quel matériau de construction combine béton et acier ?', 'Béton armé', 'forward', 'period', 'À quelle période associer l’essor du béton armé moderne ?', 'XIXe-XXe siècles', 82067),
		('invention_markers', 'Fibre de carbone', 'XXe siècle', 'International', 'La fibre de carbone est légère et résistante, utilisée dans transports, sport et industrie.', 'standard', 'general', 'Quel matériau léger et résistant est utilisé dans transports, sport et industrie ?', 'Fibre de carbone', 'forward', 'period', 'À quelle période associer l’essor de la fibre de carbone ?', 'XXe siècle', 82068),
		('invention_markers', 'Kevlar', 'XXe siècle', 'États-Unis', 'Le Kevlar est une fibre synthétique résistante associée à des usages de protection.', 'standard', 'general', 'Quelle fibre synthétique résistante est associée à des usages de protection ?', 'Kevlar', 'forward', 'period', 'À quelle période associer le Kevlar ?', 'XXe siècle', 82069),
		('invention_markers', 'Agriculture mécanisée', 'XIXe-XXe siècles', 'International', 'L’agriculture mécanisée utilise des machines pour labourer, semer, récolter ou traiter.', 'standard', 'general', 'Quelle transformation agricole utilise des machines pour labourer, semer ou récolter ?', 'Agriculture mécanisée', 'forward', 'period', 'À quelle période associer l’essor de l’agriculture mécanisée ?', 'XIXe-XXe siècles', 82070),
		('invention_markers', 'Engrais de synthèse', 'XXe siècle', 'International', 'Les engrais de synthèse augmentent les rendements agricoles grâce à la chimie industrielle.', 'standard', 'general', 'Quels produits chimiques augmentent les rendements agricoles modernes ?', 'Engrais de synthèse', 'forward', 'period', 'À quelle période associer l’essor des engrais de synthèse ?', 'XXe siècle', 82071),
		('invention_markers', 'Conservation alimentaire', 'XIXe-XXe siècles', 'International', 'La conservation alimentaire regroupe appertisation, froid, pasteurisation et emballage.', 'standard', 'general', 'Quel domaine regroupe appertisation, froid, pasteurisation et emballage ?', 'Conservation alimentaire', 'forward', 'period', 'À quelle période associer l’essor de la conservation alimentaire moderne ?', 'XIXe-XXe siècles', 82072),
		('invention_markers', 'Traitement de l’eau', 'XIXe-XXe siècles', 'International', 'Le traitement de l’eau rend l’eau plus sûre par filtration, désinfection ou procédés chimiques.', 'standard', 'general', 'Quel domaine rend l’eau plus sûre par filtration ou désinfection ?', 'Traitement de l’eau', 'forward', 'period', 'À quelle période associer l’essor du traitement moderne de l’eau ?', 'XIXe-XXe siècles', 82073),
		('invention_markers', 'Recyclage industriel', 'XXe-XXIe siècles', 'International', 'Le recyclage industriel transforme des déchets en matières réutilisables.', 'standard', 'general', 'Quelle pratique transforme des déchets en matières réutilisables ?', 'Recyclage industriel', 'forward', 'period', 'À quelle période associer l’essor du recyclage industriel moderne ?', 'XXe-XXIe siècles', 82074)
	) as values_table(collection, title, period_label, location_label, short_summary, primary_direction, primary_type, primary_question, primary_answer, secondary_direction, secondary_type, secondary_question, secondary_answer, sort_order)
), inserted_items as (
	insert into public.culture_items (
		category,
		item_type,
		collection,
		title,
		period_label,
		location_label,
		short_summary,
		sort_order
	)
	select
		'inventions',
		case
			when source_items.collection = 'invention_markers' then 'cultural_marker'
			else 'knowledge_card'
		end,
		source_items.collection,
		source_items.title,
		source_items.period_label,
		source_items.location_label,
		source_items.short_summary,
		source_items.sort_order
	from source_items
	where not exists (
		select 1
		from public.culture_items existing_items
		where existing_items.category = 'inventions'
			and existing_items.collection = source_items.collection
			and existing_items.title = source_items.title
	)
	returning id, collection, title
), source_prompts as (
	select
		source_items.collection,
		source_items.title as item_title,
		source_items.primary_direction as prompt_direction,
		source_items.primary_type as prompt_type,
		source_items.primary_question as question,
		source_items.primary_answer as answer,
		10 as sort_order
	from source_items
	where source_items.primary_question is not null

	union all

	select
		source_items.collection,
		source_items.title as item_title,
		source_items.secondary_direction as prompt_direction,
		source_items.secondary_type as prompt_type,
		source_items.secondary_question as question,
		source_items.secondary_answer as answer,
		20 as sort_order
	from source_items
	where source_items.secondary_question is not null
), all_invention_items as (
	select inserted_items.id, inserted_items.collection, inserted_items.title
	from inserted_items

	union all

	select existing_items.id, existing_items.collection, existing_items.title
	from public.culture_items existing_items
	join source_items
		on source_items.collection = existing_items.collection
		and source_items.title = existing_items.title
	where existing_items.category = 'inventions'
)
insert into public.culture_prompts (
	item_id,
	prompt_direction,
	prompt_type,
	question,
	answer,
	answer_aliases,
	choices,
	sort_order
)
select
	all_invention_items.id,
	source_prompts.prompt_direction,
	source_prompts.prompt_type,
	source_prompts.question,
	source_prompts.answer,
	array[]::text[],
	array[]::text[],
	source_prompts.sort_order
from source_prompts
join all_invention_items
	on all_invention_items.collection = source_prompts.collection
	and all_invention_items.title = source_prompts.item_title
where not exists (
	select 1
	from public.culture_prompts existing_prompts
	where existing_prompts.item_id = all_invention_items.id
		and existing_prompts.question = source_prompts.question
);

-- Requêtes de contrôle utiles après application réelle :
-- select collection, count(*) from public.culture_items where category = 'inventions' and collection in ('invention_dates', 'invention_people', 'invention_markers') group by collection order by collection;
-- select culture_items.collection, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'inventions' and culture_items.collection in ('invention_dates', 'invention_people', 'invention_markers') group by culture_items.collection order by culture_items.collection;
-- select culture_prompts.prompt_type, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'inventions' and culture_items.collection in ('invention_dates', 'invention_people', 'invention_markers') group by culture_prompts.prompt_type order by culture_prompts.prompt_type;
-- select culture_prompts.question, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'inventions' and culture_items.collection in ('invention_dates', 'invention_people', 'invention_markers') group by culture_prompts.question having count(*) > 1 order by count(*) desc, culture_prompts.question;
-- select collection, title, count(*) from public.culture_items where category = 'inventions' and collection in ('invention_dates', 'invention_people', 'invention_markers') group by collection, title having count(*) > 1 order by collection, title;
