-- Seed Culture / Cinéma : films, réalisateurs, figures et repères de cinéma.
-- Cette migration ajoute uniquement du contenu read-only dans les tables Culture existantes.
-- Elle est idempotente et ne modifie pas le schéma.
-- Les films Le Parrain et Pulp Fiction existent déjà dans le seed Culture initial et ne sont pas réinsérés ici.

with source_items as (
	select *
	from (
	values
		('cinema_film_dates', 'Voyage dans la Lune', '1902', 'France', 'Film de Georges Méliès, sorti en 1902.', 'forward', 'director', 'Qui a réalisé Voyage dans la Lune ?', 'Georges Méliès', 'forward', 'date', 'En quelle année est sorti Voyage dans la Lune ?', '1902', 70000),
		('cinema_film_dates', 'Le Cuirassé Potemkine', '1925', 'URSS', 'Film de Sergueï Eisenstein, sorti en 1925.', 'forward', 'director', 'Qui a réalisé Le Cuirassé Potemkine ?', 'Sergueï Eisenstein', 'forward', 'date', 'En quelle année est sorti Le Cuirassé Potemkine ?', '1925', 70001),
		('cinema_film_dates', 'Metropolis', '1927', 'Allemagne', 'Film de Fritz Lang, sorti en 1927.', 'forward', 'director', 'Qui a réalisé Metropolis ?', 'Fritz Lang', 'forward', 'date', 'En quelle année est sorti Metropolis ?', '1927', 70002),
		('cinema_film_dates', 'La Passion de Jeanne d’Arc', '1928', 'France', 'Film de Carl Theodor Dreyer, sorti en 1928.', 'forward', 'director', 'Qui a réalisé La Passion de Jeanne d’Arc ?', 'Carl Theodor Dreyer', 'forward', 'date', 'En quelle année est sorti La Passion de Jeanne d’Arc ?', '1928', 70003),
		('cinema_film_dates', 'Un chien andalou', '1929', 'France', 'Film de Luis Buñuel, sorti en 1929.', 'forward', 'director', 'Qui a réalisé Un chien andalou ?', 'Luis Buñuel', 'forward', 'date', 'En quelle année est sorti Un chien andalou ?', '1929', 70004),
		('cinema_film_dates', 'M le maudit', '1931', 'Allemagne', 'Film de Fritz Lang, sorti en 1931.', 'forward', 'director', 'Qui a réalisé M le maudit ?', 'Fritz Lang', 'forward', 'date', 'En quelle année est sorti M le maudit ?', '1931', 70005),
		('cinema_film_dates', 'Les Temps modernes', '1936', 'États-Unis', 'Film de Charlie Chaplin, sorti en 1936.', 'forward', 'director', 'Qui a réalisé Les Temps modernes ?', 'Charlie Chaplin', 'forward', 'date', 'En quelle année est sorti Les Temps modernes ?', '1936', 70006),
		('cinema_film_dates', 'La Grande Illusion', '1937', 'France', 'Film de Jean Renoir, sorti en 1937.', 'forward', 'director', 'Qui a réalisé La Grande Illusion ?', 'Jean Renoir', 'forward', 'date', 'En quelle année est sorti La Grande Illusion ?', '1937', 70007),
		('cinema_film_dates', 'Le Magicien d’Oz', '1939', 'États-Unis', 'Film de Victor Fleming, sorti en 1939.', 'forward', 'director', 'Qui a réalisé Le Magicien d’Oz ?', 'Victor Fleming', 'forward', 'date', 'En quelle année est sorti Le Magicien d’Oz ?', '1939', 70008),
		('cinema_film_dates', 'Citizen Kane', '1941', 'États-Unis', 'Film d’Orson Welles, sorti en 1941.', 'forward', 'director', 'Qui a réalisé Citizen Kane ?', 'Orson Welles', 'forward', 'date', 'En quelle année est sorti Citizen Kane ?', '1941', 70009),
		('cinema_film_dates', 'Casablanca', '1942', 'États-Unis', 'Film de Michael Curtiz, sorti en 1942.', 'forward', 'director', 'Qui a réalisé Casablanca ?', 'Michael Curtiz', 'forward', 'date', 'En quelle année est sorti Casablanca ?', '1942', 70010),
		('cinema_film_dates', 'Rome, ville ouverte', '1945', 'Italie', 'Film de Roberto Rossellini, sorti en 1945.', 'forward', 'director', 'Qui a réalisé Rome, ville ouverte ?', 'Roberto Rossellini', 'forward', 'date', 'En quelle année est sorti Rome, ville ouverte ?', '1945', 70011),
		('cinema_film_dates', 'Voleur de bicyclette', '1948', 'Italie', 'Film de Vittorio De Sica, sorti en 1948.', 'forward', 'director', 'Qui a réalisé Voleur de bicyclette ?', 'Vittorio De Sica', 'forward', 'date', 'En quelle année est sorti Voleur de bicyclette ?', '1948', 70012),
		('cinema_film_dates', 'Rashomon', '1950', 'Japon', 'Film d’Akira Kurosawa, sorti en 1950.', 'forward', 'director', 'Qui a réalisé Rashomon ?', 'Akira Kurosawa', 'forward', 'date', 'En quelle année est sorti Rashomon ?', '1950', 70013),
		('cinema_film_dates', 'Chantons sous la pluie', '1952', 'États-Unis', 'Film de Stanley Donen et Gene Kelly, sorti en 1952.', 'forward', 'director', 'Qui a réalisé Chantons sous la pluie ?', 'Stanley Donen et Gene Kelly', 'forward', 'date', 'En quelle année est sorti Chantons sous la pluie ?', '1952', 70014),
		('cinema_film_dates', 'Voyage à Tokyo', '1953', 'Japon', 'Film de Yasujiro Ozu, sorti en 1953.', 'forward', 'director', 'Qui a réalisé Voyage à Tokyo ?', 'Yasujiro Ozu', 'forward', 'date', 'En quelle année est sorti Voyage à Tokyo ?', '1953', 70015),
		('cinema_film_dates', 'Les Sept Samouraïs', '1954', 'Japon', 'Film d’Akira Kurosawa, sorti en 1954.', 'forward', 'director', 'Qui a réalisé Les Sept Samouraïs ?', 'Akira Kurosawa', 'forward', 'date', 'En quelle année est sorti Les Sept Samouraïs ?', '1954', 70016),
		('cinema_film_dates', 'Fenêtre sur cour', '1954', 'États-Unis', 'Film d’Alfred Hitchcock, sorti en 1954.', 'forward', 'director', 'Qui a réalisé Fenêtre sur cour ?', 'Alfred Hitchcock', 'forward', 'date', 'En quelle année est sorti Fenêtre sur cour ?', '1954', 70017),
		('cinema_film_dates', 'La Nuit du chasseur', '1955', 'États-Unis', 'Film de Charles Laughton, sorti en 1955.', 'forward', 'director', 'Qui a réalisé La Nuit du chasseur ?', 'Charles Laughton', 'forward', 'date', 'En quelle année est sorti La Nuit du chasseur ?', '1955', 70018),
		('cinema_film_dates', 'La Prisonnière du désert', '1956', 'États-Unis', 'Film de John Ford, sorti en 1956.', 'forward', 'director', 'Qui a réalisé La Prisonnière du désert ?', 'John Ford', 'forward', 'date', 'En quelle année est sorti La Prisonnière du désert ?', '1956', 70019),
		('cinema_film_dates', 'Les Quatre Cents Coups', '1959', 'France', 'Film de François Truffaut, sorti en 1959.', 'forward', 'director', 'Qui a réalisé Les Quatre Cents Coups ?', 'François Truffaut', 'forward', 'date', 'En quelle année est sorti Les Quatre Cents Coups ?', '1959', 70020),
		('cinema_film_dates', 'À bout de souffle', '1960', 'France', 'Film de Jean-Luc Godard, sorti en 1960.', 'forward', 'director', 'Qui a réalisé À bout de souffle ?', 'Jean-Luc Godard', 'forward', 'date', 'En quelle année est sorti À bout de souffle ?', '1960', 70021),
		('cinema_film_dates', 'Psychose', '1960', 'États-Unis', 'Film d’Alfred Hitchcock, sorti en 1960.', 'forward', 'director', 'Qui a réalisé Psychose ?', 'Alfred Hitchcock', 'forward', 'date', 'En quelle année est sorti Psychose ?', '1960', 70022),
		('cinema_film_dates', 'La Dolce Vita', '1960', 'Italie', 'Film de Federico Fellini, sorti en 1960.', 'forward', 'director', 'Qui a réalisé La Dolce Vita ?', 'Federico Fellini', 'forward', 'date', 'En quelle année est sorti La Dolce Vita ?', '1960', 70023),
		('cinema_film_dates', 'West Side Story', '1961', 'États-Unis', 'Film de Robert Wise et Jerome Robbins, sorti en 1961.', 'forward', 'director', 'Qui a réalisé West Side Story ?', 'Robert Wise et Jerome Robbins', 'forward', 'date', 'En quelle année est sorti West Side Story ?', '1961', 70024),
		('cinema_film_dates', 'Lawrence d’Arabie', '1962', 'Royaume-Uni', 'Film de David Lean, sorti en 1962.', 'forward', 'director', 'Qui a réalisé Lawrence d’Arabie ?', 'David Lean', 'forward', 'date', 'En quelle année est sorti Lawrence d’Arabie ?', '1962', 70025),
		('cinema_film_dates', 'Huit et demi', '1963', 'Italie', 'Film de Federico Fellini, sorti en 1963.', 'forward', 'director', 'Qui a réalisé Huit et demi ?', 'Federico Fellini', 'forward', 'date', 'En quelle année est sorti Huit et demi ?', '1963', 70026),
		('cinema_film_dates', 'Les Parapluies de Cherbourg', '1964', 'France', 'Film de Jacques Demy, sorti en 1964.', 'forward', 'director', 'Qui a réalisé Les Parapluies de Cherbourg ?', 'Jacques Demy', 'forward', 'date', 'En quelle année est sorti Les Parapluies de Cherbourg ?', '1964', 70027),
		('cinema_film_dates', 'Le Bon, la Brute et le Truand', '1966', 'Italie', 'Film de Sergio Leone, sorti en 1966.', 'forward', 'director', 'Qui a réalisé Le Bon, la Brute et le Truand ?', 'Sergio Leone', 'forward', 'date', 'En quelle année est sorti Le Bon, la Brute et le Truand ?', '1966', 70028),
		('cinema_film_dates', '2001, l’Odyssée de l’espace', '1968', 'Royaume-Uni et États-Unis', 'Film de Stanley Kubrick, sorti en 1968.', 'forward', 'director', 'Qui a réalisé 2001, l’Odyssée de l’espace ?', 'Stanley Kubrick', 'forward', 'date', 'En quelle année est sorti 2001, l’Odyssée de l’espace ?', '1968', 70029),
		('cinema_film_dates', 'La Planète des singes', '1968', 'États-Unis', 'Film de Franklin J. Schaffner, sorti en 1968.', 'forward', 'director', 'Qui a réalisé La Planète des singes ?', 'Franklin J. Schaffner', 'forward', 'date', 'En quelle année est sorti La Planète des singes ?', '1968', 70030),
		('cinema_film_dates', 'Easy Rider', '1969', 'États-Unis', 'Film de Dennis Hopper, sorti en 1969.', 'forward', 'director', 'Qui a réalisé Easy Rider ?', 'Dennis Hopper', 'forward', 'date', 'En quelle année est sorti Easy Rider ?', '1969', 70031),
		('cinema_film_dates', 'Le Conformiste', '1970', 'Italie', 'Film de Bernardo Bertolucci, sorti en 1970.', 'forward', 'director', 'Qui a réalisé Le Conformiste ?', 'Bernardo Bertolucci', 'forward', 'date', 'En quelle année est sorti Le Conformiste ?', '1970', 70032),
		('cinema_film_dates', 'Orange mécanique', '1971', 'Royaume-Uni', 'Film de Stanley Kubrick, sorti en 1971.', 'forward', 'director', 'Qui a réalisé Orange mécanique ?', 'Stanley Kubrick', 'forward', 'date', 'En quelle année est sorti Orange mécanique ?', '1971', 70033),
		('cinema_film_dates', 'Le Charme discret de la bourgeoisie', '1972', 'France', 'Film de Luis Buñuel, sorti en 1972.', 'forward', 'director', 'Qui a réalisé Le Charme discret de la bourgeoisie ?', 'Luis Buñuel', 'forward', 'date', 'En quelle année est sorti Le Charme discret de la bourgeoisie ?', '1972', 70034),
		('cinema_film_dates', 'Aguirre, la colère de Dieu', '1972', 'Allemagne', 'Film de Werner Herzog, sorti en 1972.', 'forward', 'director', 'Qui a réalisé Aguirre, la colère de Dieu ?', 'Werner Herzog', 'forward', 'date', 'En quelle année est sorti Aguirre, la colère de Dieu ?', '1972', 70035),
		('cinema_film_dates', 'La Nuit américaine', '1973', 'France', 'Film de François Truffaut, sorti en 1973.', 'forward', 'director', 'Qui a réalisé La Nuit américaine ?', 'François Truffaut', 'forward', 'date', 'En quelle année est sorti La Nuit américaine ?', '1973', 70036),
		('cinema_film_dates', 'Les Dents de la mer', '1975', 'États-Unis', 'Film de Steven Spielberg, sorti en 1975.', 'forward', 'director', 'Qui a réalisé Les Dents de la mer ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti Les Dents de la mer ?', '1975', 70037),
		('cinema_film_dates', 'Vol au-dessus d’un nid de coucou', '1975', 'États-Unis', 'Film de Miloš Forman, sorti en 1975.', 'forward', 'director', 'Qui a réalisé Vol au-dessus d’un nid de coucou ?', 'Miloš Forman', 'forward', 'date', 'En quelle année est sorti Vol au-dessus d’un nid de coucou ?', '1975', 70038),
		('cinema_film_dates', 'Taxi Driver', '1976', 'États-Unis', 'Film de Martin Scorsese, sorti en 1976.', 'forward', 'director', 'Qui a réalisé Taxi Driver ?', 'Martin Scorsese', 'forward', 'date', 'En quelle année est sorti Taxi Driver ?', '1976', 70039),
		('cinema_film_dates', 'Star Wars : Un nouvel espoir', '1977', 'États-Unis', 'Film de George Lucas, sorti en 1977.', 'forward', 'director', 'Qui a réalisé Star Wars : Un nouvel espoir ?', 'George Lucas', 'forward', 'date', 'En quelle année est sorti Star Wars : Un nouvel espoir ?', '1977', 70040),
		('cinema_film_dates', 'Rencontres du troisième type', '1977', 'États-Unis', 'Film de Steven Spielberg, sorti en 1977.', 'forward', 'director', 'Qui a réalisé Rencontres du troisième type ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti Rencontres du troisième type ?', '1977', 70041),
		('cinema_film_dates', 'Alien', '1979', 'Royaume-Uni et États-Unis', 'Film de Ridley Scott, sorti en 1979.', 'forward', 'director', 'Qui a réalisé Alien ?', 'Ridley Scott', 'forward', 'date', 'En quelle année est sorti Alien ?', '1979', 70042),
		('cinema_film_dates', 'Apocalypse Now', '1979', 'États-Unis', 'Film de Francis Ford Coppola, sorti en 1979.', 'forward', 'director', 'Qui a réalisé Apocalypse Now ?', 'Francis Ford Coppola', 'forward', 'date', 'En quelle année est sorti Apocalypse Now ?', '1979', 70043),
		('cinema_film_dates', 'Shining', '1980', 'Royaume-Uni et États-Unis', 'Film de Stanley Kubrick, sorti en 1980.', 'forward', 'director', 'Qui a réalisé Shining ?', 'Stanley Kubrick', 'forward', 'date', 'En quelle année est sorti Shining ?', '1980', 70044),
		('cinema_film_dates', 'Les Aventuriers de l’arche perdue', '1981', 'États-Unis', 'Film de Steven Spielberg, sorti en 1981.', 'forward', 'director', 'Qui a réalisé Les Aventuriers de l’arche perdue ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti Les Aventuriers de l’arche perdue ?', '1981', 70045),
		('cinema_film_dates', 'Blade Runner', '1982', 'États-Unis', 'Film de Ridley Scott, sorti en 1982.', 'forward', 'director', 'Qui a réalisé Blade Runner ?', 'Ridley Scott', 'forward', 'date', 'En quelle année est sorti Blade Runner ?', '1982', 70046),
		('cinema_film_dates', 'E.T. l’extra-terrestre', '1982', 'États-Unis', 'Film de Steven Spielberg, sorti en 1982.', 'forward', 'director', 'Qui a réalisé E.T. l’extra-terrestre ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti E.T. l’extra-terrestre ?', '1982', 70047),
		('cinema_film_dates', 'Fanny et Alexandre', '1982', 'Suède', 'Film d’Ingmar Bergman, sorti en 1982.', 'forward', 'director', 'Qui a réalisé Fanny et Alexandre ?', 'Ingmar Bergman', 'forward', 'date', 'En quelle année est sorti Fanny et Alexandre ?', '1982', 70048),
		('cinema_film_dates', 'Scarface', '1983', 'États-Unis', 'Film de Brian De Palma, sorti en 1983.', 'forward', 'director', 'Qui a réalisé Scarface ?', 'Brian De Palma', 'forward', 'date', 'En quelle année est sorti Scarface ?', '1983', 70049),
		('cinema_film_dates', 'Paris, Texas', '1984', 'Allemagne et France', 'Film de Wim Wenders, sorti en 1984.', 'forward', 'director', 'Qui a réalisé Paris, Texas ?', 'Wim Wenders', 'forward', 'date', 'En quelle année est sorti Paris, Texas ?', '1984', 70050),
		('cinema_film_dates', 'Retour vers le futur', '1985', 'États-Unis', 'Film de Robert Zemeckis, sorti en 1985.', 'forward', 'director', 'Qui a réalisé Retour vers le futur ?', 'Robert Zemeckis', 'forward', 'date', 'En quelle année est sorti Retour vers le futur ?', '1985', 70051),
		('cinema_film_dates', 'Brazil', '1985', 'Royaume-Uni', 'Film de Terry Gilliam, sorti en 1985.', 'forward', 'director', 'Qui a réalisé Brazil ?', 'Terry Gilliam', 'forward', 'date', 'En quelle année est sorti Brazil ?', '1985', 70052),
		('cinema_film_dates', 'Blue Velvet', '1986', 'États-Unis', 'Film de David Lynch, sorti en 1986.', 'forward', 'director', 'Qui a réalisé Blue Velvet ?', 'David Lynch', 'forward', 'date', 'En quelle année est sorti Blue Velvet ?', '1986', 70053),
		('cinema_film_dates', 'Le Festin de Babette', '1987', 'Danemark', 'Film de Gabriel Axel, sorti en 1987.', 'forward', 'director', 'Qui a réalisé Le Festin de Babette ?', 'Gabriel Axel', 'forward', 'date', 'En quelle année est sorti Le Festin de Babette ?', '1987', 70054),
		('cinema_film_dates', 'Akira', '1988', 'Japon', 'Film de Katsuhiro Otomo, sorti en 1988.', 'forward', 'director', 'Qui a réalisé Akira ?', 'Katsuhiro Otomo', 'forward', 'date', 'En quelle année est sorti Akira ?', '1988', 70055),
		('cinema_film_dates', 'Mon voisin Totoro', '1988', 'Japon', 'Film de Hayao Miyazaki, sorti en 1988.', 'forward', 'director', 'Qui a réalisé Mon voisin Totoro ?', 'Hayao Miyazaki', 'forward', 'date', 'En quelle année est sorti Mon voisin Totoro ?', '1988', 70056),
		('cinema_film_dates', 'Le Cercle des poètes disparus', '1989', 'États-Unis', 'Film de Peter Weir, sorti en 1989.', 'forward', 'director', 'Qui a réalisé Le Cercle des poètes disparus ?', 'Peter Weir', 'forward', 'date', 'En quelle année est sorti Le Cercle des poètes disparus ?', '1989', 70057),
		('cinema_film_dates', 'Do the Right Thing', '1989', 'États-Unis', 'Film de Spike Lee, sorti en 1989.', 'forward', 'director', 'Qui a réalisé Do the Right Thing ?', 'Spike Lee', 'forward', 'date', 'En quelle année est sorti Do the Right Thing ?', '1989', 70058),
		('cinema_film_dates', 'Les Affranchis', '1990', 'États-Unis', 'Film de Martin Scorsese, sorti en 1990.', 'forward', 'director', 'Qui a réalisé Les Affranchis ?', 'Martin Scorsese', 'forward', 'date', 'En quelle année est sorti Les Affranchis ?', '1990', 70059),
		('cinema_film_dates', 'Le Silence des agneaux', '1991', 'États-Unis', 'Film de Jonathan Demme, sorti en 1991.', 'forward', 'director', 'Qui a réalisé Le Silence des agneaux ?', 'Jonathan Demme', 'forward', 'date', 'En quelle année est sorti Le Silence des agneaux ?', '1991', 70060),
		('cinema_film_dates', 'Impitoyable', '1992', 'États-Unis', 'Film de Clint Eastwood, sorti en 1992.', 'forward', 'director', 'Qui a réalisé Impitoyable ?', 'Clint Eastwood', 'forward', 'date', 'En quelle année est sorti Impitoyable ?', '1992', 70061),
		('cinema_film_dates', 'Jurassic Park', '1993', 'États-Unis', 'Film de Steven Spielberg, sorti en 1993.', 'forward', 'director', 'Qui a réalisé Jurassic Park ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti Jurassic Park ?', '1993', 70062),
		('cinema_film_dates', 'La Liste de Schindler', '1993', 'États-Unis', 'Film de Steven Spielberg, sorti en 1993.', 'forward', 'director', 'Qui a réalisé La Liste de Schindler ?', 'Steven Spielberg', 'forward', 'date', 'En quelle année est sorti La Liste de Schindler ?', '1993', 70063),
		('cinema_film_dates', 'Forrest Gump', '1994', 'États-Unis', 'Film de Robert Zemeckis, sorti en 1994.', 'forward', 'director', 'Qui a réalisé Forrest Gump ?', 'Robert Zemeckis', 'forward', 'date', 'En quelle année est sorti Forrest Gump ?', '1994', 70064),
		('cinema_film_dates', 'Les Évadés', '1994', 'États-Unis', 'Film de Frank Darabont, sorti en 1994.', 'forward', 'director', 'Qui a réalisé Les Évadés ?', 'Frank Darabont', 'forward', 'date', 'En quelle année est sorti Les Évadés ?', '1994', 70065),
		('cinema_film_dates', 'Chungking Express', '1994', 'Hong Kong', 'Film de Wong Kar-wai, sorti en 1994.', 'forward', 'director', 'Qui a réalisé Chungking Express ?', 'Wong Kar-wai', 'forward', 'date', 'En quelle année est sorti Chungking Express ?', '1994', 70066),
		('cinema_film_dates', 'Toy Story', '1995', 'États-Unis', 'Film de John Lasseter, sorti en 1995.', 'forward', 'director', 'Qui a réalisé Toy Story ?', 'John Lasseter', 'forward', 'date', 'En quelle année est sorti Toy Story ?', '1995', 70067),
		('cinema_film_dates', 'La Haine', '1995', 'France', 'Film de Mathieu Kassovitz, sorti en 1995.', 'forward', 'director', 'Qui a réalisé La Haine ?', 'Mathieu Kassovitz', 'forward', 'date', 'En quelle année est sorti La Haine ?', '1995', 70068),
		('cinema_film_dates', 'Fargo', '1996', 'États-Unis', 'Film de Joel Coen, sorti en 1996.', 'forward', 'director', 'Qui a réalisé Fargo ?', 'Joel Coen', 'forward', 'date', 'En quelle année est sorti Fargo ?', '1996', 70069),
		('cinema_film_dates', 'Princesse Mononoke', '1997', 'Japon', 'Film de Hayao Miyazaki, sorti en 1997.', 'forward', 'director', 'Qui a réalisé Princesse Mononoke ?', 'Hayao Miyazaki', 'forward', 'date', 'En quelle année est sorti Princesse Mononoke ?', '1997', 70070),
		('cinema_film_dates', 'Titanic', '1997', 'États-Unis', 'Film de James Cameron, sorti en 1997.', 'forward', 'director', 'Qui a réalisé Titanic ?', 'James Cameron', 'forward', 'date', 'En quelle année est sorti Titanic ?', '1997', 70071),
		('cinema_film_dates', 'Matrix', '1999', 'États-Unis', 'Film des Wachowski, sorti en 1999.', 'forward', 'director', 'Qui a réalisé Matrix ?', 'Les Wachowski', 'forward', 'date', 'En quelle année est sorti Matrix ?', '1999', 70072),
		('cinema_film_dates', 'In the Mood for Love', '2000', 'Hong Kong', 'Film de Wong Kar-wai, sorti en 2000.', 'forward', 'director', 'Qui a réalisé In the Mood for Love ?', 'Wong Kar-wai', 'forward', 'date', 'En quelle année est sorti In the Mood for Love ?', '2000', 70073),
		('cinema_film_dates', 'Le Voyage de Chihiro', '2001', 'Japon', 'Film de Hayao Miyazaki, sorti en 2001.', 'forward', 'director', 'Qui a réalisé Le Voyage de Chihiro ?', 'Hayao Miyazaki', 'forward', 'date', 'En quelle année est sorti Le Voyage de Chihiro ?', '2001', 70074),
		('cinema_film_dates', 'Le Fabuleux Destin d’Amelie Poulain', '2001', 'France', 'Film de Jean-Pierre Jeunet, sorti en 2001.', 'forward', 'director', 'Qui a réalisé Le Fabuleux Destin d’Amelie Poulain ?', 'Jean-Pierre Jeunet', 'forward', 'date', 'En quelle année est sorti Le Fabuleux Destin d’Amelie Poulain ?', '2001', 70075),
		('cinema_film_dates', 'Le Seigneur des anneaux : La Communauté de l’anneau', '2001', 'Nouvelle-Zélande et États-Unis', 'Film de Peter Jackson, sorti en 2001.', 'forward', 'director', 'Qui a réalisé Le Seigneur des anneaux : La Communauté de l’anneau ?', 'Peter Jackson', 'forward', 'date', 'En quelle année est sorti Le Seigneur des anneaux : La Communauté de l’anneau ?', '2001', 70076),
		('cinema_film_dates', 'Cidade de Deus', '2002', 'Brésil', 'Film de Fernando Meirelles et Katia Lund, sorti en 2002.', 'forward', 'director', 'Qui a réalisé Cidade de Deus ?', 'Fernando Meirelles et Katia Lund', 'forward', 'date', 'En quelle année est sorti Cidade de Deus ?', '2002', 70077),
		('cinema_film_dates', 'Oldboy', '2003', 'Corée du Sud', 'Film de Park Chan-wook, sorti en 2003.', 'forward', 'director', 'Qui a réalisé Oldboy ?', 'Park Chan-wook', 'forward', 'date', 'En quelle année est sorti Oldboy ?', '2003', 70078),
		('cinema_film_dates', 'Lost in Translation', '2003', 'États-Unis', 'Film de Sofia Coppola, sorti en 2003.', 'forward', 'director', 'Qui a réalisé Lost in Translation ?', 'Sofia Coppola', 'forward', 'date', 'En quelle année est sorti Lost in Translation ?', '2003', 70079),
		('cinema_film_dates', 'Eternal Sunshine of the Spotless Mind', '2004', 'États-Unis', 'Film de Michel Gondry, sorti en 2004.', 'forward', 'director', 'Qui a réalisé Eternal Sunshine of the Spotless Mind ?', 'Michel Gondry', 'forward', 'date', 'En quelle année est sorti Eternal Sunshine of the Spotless Mind ?', '2004', 70080),
		('cinema_film_dates', 'Le Secret de Brokeback Mountain', '2005', 'États-Unis', 'Film d’Ang Lee, sorti en 2005.', 'forward', 'director', 'Qui a réalisé Le Secret de Brokeback Mountain ?', 'Ang Lee', 'forward', 'date', 'En quelle année est sorti Le Secret de Brokeback Mountain ?', '2005', 70081),
		('cinema_film_dates', 'Le Labyrinthe de Pan', '2006', 'Mexique et Espagne', 'Film de Guillermo del Toro, sorti en 2006.', 'forward', 'director', 'Qui a réalisé Le Labyrinthe de Pan ?', 'Guillermo del Toro', 'forward', 'date', 'En quelle année est sorti Le Labyrinthe de Pan ?', '2006', 70082),
		('cinema_film_dates', 'The Dark Knight', '2008', 'États-Unis', 'Film de Christopher Nolan, sorti en 2008.', 'forward', 'director', 'Qui a réalisé The Dark Knight ?', 'Christopher Nolan', 'forward', 'date', 'En quelle année est sorti The Dark Knight ?', '2008', 70083),
		('cinema_film_dates', 'Slumdog Millionaire', '2008', 'Royaume-Uni et Inde', 'Film de Danny Boyle, sorti en 2008.', 'forward', 'director', 'Qui a réalisé Slumdog Millionaire ?', 'Danny Boyle', 'forward', 'date', 'En quelle année est sorti Slumdog Millionaire ?', '2008', 70084),
		('cinema_film_dates', 'Avatar', '2009', 'États-Unis', 'Film de James Cameron, sorti en 2009.', 'forward', 'director', 'Qui a réalisé Avatar ?', 'James Cameron', 'forward', 'date', 'En quelle année est sorti Avatar ?', '2009', 70085),
		('cinema_film_dates', 'Une séparation', '2011', 'Iran', 'Film d’Asghar Farhadi, sorti en 2011.', 'forward', 'director', 'Qui a réalisé Une séparation ?', 'Asghar Farhadi', 'forward', 'date', 'En quelle année est sorti Une séparation ?', '2011', 70086),
		('cinema_film_dates', 'The Artist', '2011', 'France', 'Film de Michel Hazanavicius, sorti en 2011.', 'forward', 'director', 'Qui a réalisé The Artist ?', 'Michel Hazanavicius', 'forward', 'date', 'En quelle année est sorti The Artist ?', '2011', 70087),
		('cinema_film_dates', 'Intouchables', '2011', 'France', 'Film d’Olivier Nakache et Eric Toledano, sorti en 2011.', 'forward', 'director', 'Qui a réalisé Intouchables ?', 'Olivier Nakache et Eric Toledano', 'forward', 'date', 'En quelle année est sorti Intouchables ?', '2011', 70088),
		('cinema_film_dates', 'Ida', '2013', 'Pologne', 'Film de Paweł Pawlikowski, sorti en 2013.', 'forward', 'director', 'Qui a réalisé Ida ?', 'Paweł Pawlikowski', 'forward', 'date', 'En quelle année est sorti Ida ?', '2013', 70089),
		('cinema_film_dates', 'Timbuktu', '2014', 'Mauritanie et France', 'Film d’Abderrahmane Sissako, sorti en 2014.', 'forward', 'director', 'Qui a réalisé Timbuktu ?', 'Abderrahmane Sissako', 'forward', 'date', 'En quelle année est sorti Timbuktu ?', '2014', 70090),
		('cinema_film_dates', 'Whiplash', '2014', 'États-Unis', 'Film de Damien Chazelle, sorti en 2014.', 'forward', 'director', 'Qui a réalisé Whiplash ?', 'Damien Chazelle', 'forward', 'date', 'En quelle année est sorti Whiplash ?', '2014', 70091),
		('cinema_film_dates', 'Mad Max: Fury Road', '2015', 'Australie', 'Film de George Miller, sorti en 2015.', 'forward', 'director', 'Qui a réalisé Mad Max: Fury Road ?', 'George Miller', 'forward', 'date', 'En quelle année est sorti Mad Max: Fury Road ?', '2015', 70092),
		('cinema_film_dates', 'Moonlight', '2016', 'États-Unis', 'Film de Barry Jenkins, sorti en 2016.', 'forward', 'director', 'Qui a réalisé Moonlight ?', 'Barry Jenkins', 'forward', 'date', 'En quelle année est sorti Moonlight ?', '2016', 70093),
		('cinema_film_dates', 'La La Land', '2016', 'États-Unis', 'Film de Damien Chazelle, sorti en 2016.', 'forward', 'director', 'Qui a réalisé La La Land ?', 'Damien Chazelle', 'forward', 'date', 'En quelle année est sorti La La Land ?', '2016', 70094),
		('cinema_film_dates', 'Get Out', '2017', 'États-Unis', 'Film de Jordan Peele, sorti en 2017.', 'forward', 'director', 'Qui a réalisé Get Out ?', 'Jordan Peele', 'forward', 'date', 'En quelle année est sorti Get Out ?', '2017', 70095),
		('cinema_film_dates', 'Roma', '2018', 'Mexique', 'Film d’Alfonso Cuarón, sorti en 2018.', 'forward', 'director', 'Qui a réalisé Roma ?', 'Alfonso Cuarón', 'forward', 'date', 'En quelle année est sorti Roma ?', '2018', 70096),
		('cinema_film_dates', 'Black Panther', '2018', 'États-Unis', 'Film de Ryan Coogler, sorti en 2018.', 'forward', 'director', 'Qui a réalisé Black Panther ?', 'Ryan Coogler', 'forward', 'date', 'En quelle année est sorti Black Panther ?', '2018', 70097),
		('cinema_film_dates', 'Spider-Man: New Generation', '2018', 'États-Unis', 'Film de Bob Persichetti, Peter Ramsey et Rodney Rothman, sorti en 2018.', 'forward', 'director', 'Qui a réalisé Spider-Man: New Generation ?', 'Bob Persichetti, Peter Ramsey et Rodney Rothman', 'forward', 'date', 'En quelle année est sorti Spider-Man: New Generation ?', '2018', 70098),
		('cinema_film_dates', 'Parasite', '2019', 'Corée du Sud', 'Film de Bong Joon-ho, sorti en 2019.', 'forward', 'director', 'Qui a réalisé Parasite ?', 'Bong Joon-ho', 'forward', 'date', 'En quelle année est sorti Parasite ?', '2019', 70099),
		('cinema_director_links', 'Georges Méliès', 'Cinéma muet', 'France', 'Réalisateur français associé à Voyage dans la Lune.', 'reverse', 'film', 'Quel film emblématique associer à Georges Méliès ?', 'Voyage dans la Lune', null, null, null, null, 71000),
		('cinema_director_links', 'Alice Guy', 'Cinéma muet', 'France', 'Pionniere du cinéma associée à La Fée aux choux.', 'reverse', 'film', 'Quel film emblématique associer à Alice Guy ?', 'La Fée aux choux', null, null, null, null, 71001),
		('cinema_director_links', 'Charlie Chaplin', 'Cinéma muet et parlant', 'Royaume-Uni et États-Unis', 'Cinéaste et acteur associé aux Temps modernes.', 'reverse', 'film', 'Quel film emblématique associer à Charlie Chaplin ?', 'Les Temps modernes', null, null, null, null, 71002),
		('cinema_director_links', 'Buster Keaton', 'Cinéma muet', 'États-Unis', 'Cinéaste et acteur associé au Mecanicien de la General.', 'reverse', 'film', 'Quel film emblématique associer à Buster Keaton ?', 'Le Mécano de la General', null, null, null, null, 71003),
		('cinema_director_links', 'F. W. Murnau', 'Expressionnisme', 'Allemagne et États-Unis', 'Réalisateur associé à Nosferatu.', 'reverse', 'film', 'Quel film emblématique associer à F. W. Murnau ?', 'Nosferatu', null, null, null, null, 71004),
		('cinema_director_links', 'Fritz Lang', 'Expressionnisme et film noir', 'Allemagne et États-Unis', 'Réalisateur associé à Metropolis.', 'reverse', 'film', 'Quel film emblématique associer à Fritz Lang ?', 'Metropolis', null, null, null, null, 71005),
		('cinema_director_links', 'Sergueï Eisenstein', 'Montage soviétique', 'URSS', 'Réalisateur associé au Cuirassé Potemkine.', 'reverse', 'film', 'Quel film emblématique associer à Sergueï Eisenstein ?', 'Le Cuirassé Potemkine', null, null, null, null, 71006),
		('cinema_director_links', 'Carl Theodor Dreyer', 'Cinéma europeen', 'Danemark', 'Réalisateur associé à La Passion de Jeanne d’Arc.', 'reverse', 'film', 'Quel film emblématique associer à Carl Theodor Dreyer ?', 'La Passion de Jeanne d’Arc', null, null, null, null, 71007),
		('cinema_director_links', 'Jean Renoir', 'Cinéma français', 'France', 'Réalisateur associé à La Grande Illusion.', 'reverse', 'film', 'Quel film emblématique associer à Jean Renoir ?', 'La Grande Illusion', null, null, null, null, 71008),
		('cinema_director_links', 'John Ford', 'Western', 'États-Unis', 'Réalisateur associé à La Prisonnière du désert.', 'reverse', 'film', 'Quel film emblématique associer à John Ford ?', 'La Prisonnière du désert', null, null, null, null, 71009),
		('cinema_director_links', 'Orson Welles', 'Cinéma américain', 'États-Unis', 'Réalisateur et acteur associé à Citizen Kane.', 'reverse', 'film', 'Quel film emblématique associer à Orson Welles ?', 'Citizen Kane', null, null, null, null, 71010),
		('cinema_director_links', 'Alfred Hitchcock', 'Suspense', 'Royaume-Uni et États-Unis', 'Réalisateur associé à Psychose.', 'reverse', 'film', 'Quel film emblématique associer à Alfred Hitchcock ?', 'Psychose', null, null, null, null, 71011),
		('cinema_director_links', 'Billy Wilder', 'Cinéma hollywoodien', 'États-Unis', 'Réalisateur associé à Certains l’aiment chaud.', 'reverse', 'film', 'Quel film emblématique associer à Billy Wilder ?', 'Certains l’aiment chaud', null, null, null, null, 71012),
		('cinema_director_links', 'Roberto Rossellini', 'Néoréalisme italien', 'Italie', 'Réalisateur associé à Rome, ville ouverte.', 'reverse', 'film', 'Quel film emblématique associer à Roberto Rossellini ?', 'Rome, ville ouverte', null, null, null, null, 71013),
		('cinema_director_links', 'Vittorio De Sica', 'Néoréalisme italien', 'Italie', 'Réalisateur associé à Voleur de bicyclette.', 'reverse', 'film', 'Quel film emblématique associer à Vittorio De Sica ?', 'Voleur de bicyclette', null, null, null, null, 71014),
		('cinema_director_links', 'Akira Kurosawa', 'Cinéma japonais', 'Japon', 'Réalisateur associé aux Sept Samourais.', 'reverse', 'film', 'Quel film emblématique associer à Akira Kurosawa ?', 'Les Sept Samouraïs', null, null, null, null, 71015),
		('cinema_director_links', 'Yasujiro Ozu', 'Cinéma japonais', 'Japon', 'Réalisateur associé à Voyage à Tokyo.', 'reverse', 'film', 'Quel film emblématique associer à Yasujiro Ozu ?', 'Voyage à Tokyo', null, null, null, null, 71016),
		('cinema_director_links', 'Satyajit Ray', 'Cinéma indien', 'Inde', 'Réalisateur associé à La Complainte du sentier.', 'reverse', 'film', 'Quel film emblématique associer à Satyajit Ray ?', 'La Complainte du sentier', null, null, null, null, 71017),
		('cinema_director_links', 'Ingmar Bergman', 'Cinéma suedois', 'Suède', 'Réalisateur associé au Septieme Sceau.', 'reverse', 'film', 'Quel film emblématique associer à Ingmar Bergman ?', 'Le Septieme Sceau', null, null, null, null, 71018),
		('cinema_director_links', 'Federico Fellini', 'Cinéma italien', 'Italie', 'Réalisateur associé à La Dolce Vita.', 'reverse', 'film', 'Quel film emblématique associer à Federico Fellini ?', 'La Dolce Vita', null, null, null, null, 71019),
		('cinema_director_links', 'Agnès Varda', 'Nouvelle Vague', 'France', 'Réalisatrice associée à Cléo de 5 à 7.', 'reverse', 'film', 'Quel film emblématique associer à Agnès Varda ?', 'Cléo de 5 à 7', null, null, null, null, 71020),
		('cinema_director_links', 'François Truffaut', 'Nouvelle Vague', 'France', 'Réalisateur associé aux Quatre Cents Coups.', 'reverse', 'film', 'Quel film emblématique associer à François Truffaut ?', 'Les Quatre Cents Coups', null, null, null, null, 71021),
		('cinema_director_links', 'Jean-Luc Godard', 'Nouvelle Vague', 'France', 'Réalisateur associé à À bout de souffle.', 'reverse', 'film', 'Quel film emblématique associer à Jean-Luc Godard ?', 'À bout de souffle', null, null, null, null, 71022),
		('cinema_director_links', 'Jacques Demy', 'Cinéma musical français', 'France', 'Réalisateur associé aux Parapluies de Cherbourg.', 'reverse', 'film', 'Quel film emblématique associer à Jacques Demy ?', 'Les Parapluies de Cherbourg', null, null, null, null, 71023),
		('cinema_director_links', 'Sergio Leone', 'Western spaghetti', 'Italie', 'Réalisateur associé au Bon, la Brute et le Truand.', 'reverse', 'film', 'Quel film emblématique associer à Sergio Leone ?', 'Le Bon, la Brute et le Truand', null, null, null, null, 71024),
		('cinema_director_links', 'Stanley Kubrick', 'Cinéma moderne', 'États-Unis et Royaume-Uni', 'Réalisateur associé à 2001, l’Odyssée de l’espace.', 'reverse', 'film', 'Quel film emblématique associer à Stanley Kubrick ?', '2001, l’Odyssée de l’espace', null, null, null, null, 71025),
		('cinema_director_links', 'Luis Buñuel', 'Surréalisme', 'Espagne et France', 'Réalisateur associé à Un chien andalou.', 'reverse', 'film', 'Quel film emblématique associer à Luis Buñuel ?', 'Un chien andalou', null, null, null, null, 71026),
		('cinema_director_links', 'Andrei Tarkovski', 'Cinéma sovietique', 'URSS', 'Réalisateur associé à Solaris.', 'reverse', 'film', 'Quel film emblématique associer à Andrei Tarkovski ?', 'Solaris', null, null, null, null, 71027),
		('cinema_director_links', 'Werner Herzog', 'Nouveau cinéma allemand', 'Allemagne', 'Réalisateur associé à Aguirre, la colère de Dieu.', 'reverse', 'film', 'Quel film emblématique associer à Werner Herzog ?', 'Aguirre, la colère de Dieu', null, null, null, null, 71028),
		('cinema_director_links', 'Martin Scorsese', 'Cinéma américain', 'États-Unis', 'Réalisateur associé à Taxi Driver.', 'reverse', 'film', 'Quel film emblématique associer à Martin Scorsese ?', 'Taxi Driver', null, null, null, null, 71029),
		('cinema_director_links', 'Francis Ford Coppola', 'Nouvel Hollywood', 'États-Unis', 'Réalisateur associé au Parrain.', 'reverse', 'film', 'Quel film emblématique associer à Francis Ford Coppola ?', 'Le Parrain', null, null, null, null, 71030),
		('cinema_director_links', 'Steven Spielberg', 'Cinéma populaire américain', 'États-Unis', 'Réalisateur associé aux Dents de la mer.', 'reverse', 'film', 'Quel film emblématique associer à Steven Spielberg ?', 'Les Dents de la mer', null, null, null, null, 71031),
		('cinema_director_links', 'George Lucas', 'Blockbuster et science-fiction', 'États-Unis', 'Réalisateur associé à Star Wars.', 'reverse', 'film', 'Quel film emblématique associer à George Lucas ?', 'Star Wars : Un nouvel espoir', null, null, null, null, 71032),
		('cinema_director_links', 'Ridley Scott', 'Science-fiction et thriller', 'Royaume-Uni', 'Réalisateur associé à Alien.', 'reverse', 'film', 'Quel film emblématique associer à Ridley Scott ?', 'Alien', null, null, null, null, 71033),
		('cinema_director_links', 'David Lynch', 'Cinéma américain', 'États-Unis', 'Réalisateur associé à Blue Velvet.', 'reverse', 'film', 'Quel film emblématique associer à David Lynch ?', 'Blue Velvet', null, null, null, null, 71034),
		('cinema_director_links', 'Spike Lee', 'Cinéma américain', 'États-Unis', 'Réalisateur associé à Do the Right Thing.', 'reverse', 'film', 'Quel film emblématique associer à Spike Lee ?', 'Do the Right Thing', null, null, null, null, 71035),
		('cinema_director_links', 'Kathryn Bigelow', 'Cinéma américain', 'États-Unis', 'Réalisatrice associée à Demineurs.', 'reverse', 'film', 'Quel film emblématique associer à Kathryn Bigelow ?', 'Demineurs', null, null, null, null, 71036),
		('cinema_director_links', 'Jane Campion', 'Cinéma neo-zelandais', 'Nouvelle-Zélande', 'Réalisatrice associée à La Leçon de piano.', 'reverse', 'film', 'Quel film emblématique associer à Jane Campion ?', 'La Leçon de piano', null, null, null, null, 71037),
		('cinema_director_links', 'Sofia Coppola', 'Cinéma américain', 'États-Unis', 'Réalisatrice associée à Lost in Translation.', 'reverse', 'film', 'Quel film emblématique associer à Sofia Coppola ?', 'Lost in Translation', null, null, null, null, 71038),
		('cinema_director_links', 'Chantal Akerman', 'Cinéma belge', 'Belgique', 'Réalisatrice associée à Jeanne Dielman.', 'reverse', 'film', 'Quel film emblématique associer à Chantal Akerman ?', 'Jeanne Dielman', null, null, null, null, 71039),
		('cinema_director_links', 'Claire Denis', 'Cinéma français', 'France', 'Réalisatrice associée à Beau Travail.', 'reverse', 'film', 'Quel film emblématique associer à Claire Denis ?', 'Beau Travail', null, null, null, null, 71040),
		('cinema_director_links', 'Céline Sciamma', 'Cinéma français', 'France', 'Réalisatrice associée à Portrait de la jeune fille en feu.', 'reverse', 'film', 'Quel film emblématique associer à Céline Sciamma ?', 'Portrait de la jeune fille en feu', null, null, null, null, 71041),
		('cinema_director_links', 'Hayao Miyazaki', 'Animation japonaise', 'Japon', 'Réalisateur associé au Voyage de Chihiro.', 'reverse', 'film', 'Quel film emblématique associer à Hayao Miyazaki ?', 'Le Voyage de Chihiro', null, null, null, null, 71042),
		('cinema_director_links', 'Isao Takahata', 'Animation japonaise', 'Japon', 'Réalisateur associé au Tombeau des lucioles.', 'reverse', 'film', 'Quel film emblématique associer à Isao Takahata ?', 'Le Tombeau des lucioles', null, null, null, null, 71043),
		('cinema_director_links', 'Katsuhiro Otomo', 'Animation japonaise', 'Japon', 'Réalisateur associé à Akira.', 'reverse', 'film', 'Quel film emblématique associer à Katsuhiro Otomo ?', 'Akira', null, null, null, null, 71044),
		('cinema_director_links', 'John Lasseter', 'Animation', 'États-Unis', 'Réalisateur associé à Toy Story.', 'reverse', 'film', 'Quel film emblématique associer à John Lasseter ?', 'Toy Story', null, null, null, null, 71045),
		('cinema_director_links', 'Brad Bird', 'Animation', 'États-Unis', 'Réalisateur associé aux Indestructibles.', 'reverse', 'film', 'Quel film emblématique associer à Brad Bird ?', 'Les Indestructibles', null, null, null, null, 71046),
		('cinema_director_links', 'Walt Disney', 'Animation', 'États-Unis', 'Producteur associé à Blanche-Neige et les Sept Nains.', 'reverse', 'film', 'Quel film emblématique associer à Walt Disney ?', 'Blanche-Neige et les Sept Nains', null, null, null, null, 71047),
		('cinema_director_links', 'Sembène Ousmane', 'Cinéma africain', 'Sénégal', 'Réalisateur associé à La Noire de...', 'reverse', 'film', 'Quel film emblématique associer à Sembène Ousmane ?', 'La Noire de...', null, null, null, null, 71048),
		('cinema_director_links', 'Abbas Kiarostami', 'Cinéma iranien', 'Iran', 'Réalisateur associé au Goût de la cerise.', 'reverse', 'film', 'Quel film emblématique associer à Abbas Kiarostami ?', 'Le Goût de la cerise', null, null, null, null, 71049),
		('cinema_director_links', 'Asghar Farhadi', 'Cinéma iranien', 'Iran', 'Réalisateur associé à Une séparation.', 'reverse', 'film', 'Quel film emblématique associer à Asghar Farhadi ?', 'Une séparation', null, null, null, null, 71050),
		('cinema_director_links', 'Wong Kar-wai', 'Cinéma de Hong Kong', 'Hong Kong', 'Réalisateur associé à In the Mood for Love.', 'reverse', 'film', 'Quel film emblématique associer à Wong Kar-wai ?', 'In the Mood for Love', null, null, null, null, 71051),
		('cinema_director_links', 'John Woo', 'Cinéma de Hong Kong', 'Hong Kong', 'Réalisateur associé à The Killer.', 'reverse', 'film', 'Quel film emblématique associer à John Woo ?', 'The Killer', null, null, null, null, 71052),
		('cinema_director_links', 'Ang Lee', 'Cinéma international', 'Taiwan et États-Unis', 'Réalisateur associé à Tigre et Dragon.', 'reverse', 'film', 'Quel film emblématique associer à Ang Lee ?', 'Tigre et Dragon', null, null, null, null, 71053),
		('cinema_director_links', 'Park Chan-wook', 'Cinéma sud-coréen', 'Corée du Sud', 'Réalisateur associé à Oldboy.', 'reverse', 'film', 'Quel film emblématique associer à Park Chan-wook ?', 'Oldboy', null, null, null, null, 71054),
		('cinema_director_links', 'Bong Joon-ho', 'Cinéma sud-coréen', 'Corée du Sud', 'Réalisateur associé à Parasite.', 'reverse', 'film', 'Quel film emblématique associer à Bong Joon-ho ?', 'Parasite', null, null, null, null, 71055),
		('cinema_director_links', 'Zhang Yimou', 'Cinéma chinois', 'Chine', 'Réalisateur associé à Épouses et Concubines.', 'reverse', 'film', 'Quel film emblématique associer à Zhang Yimou ?', 'Épouses et Concubines', null, null, null, null, 71056),
		('cinema_director_links', 'Edward Yang', 'Cinéma taïwanais', 'Taiwan', 'Réalisateur associé à Yi Yi.', 'reverse', 'film', 'Quel film emblématique associer à Edward Yang ?', 'Yi Yi', null, null, null, null, 71057),
		('cinema_director_links', 'Apichatpong Weerasethakul', 'Cinéma thaïlandais', 'Thaïlande', 'Réalisateur associé à Oncle Boonmee.', 'reverse', 'film', 'Quel film emblématique associer à Apichatpong Weerasethakul ?', 'Oncle Boonmee', null, null, null, null, 71058),
		('cinema_director_links', 'Guillermo del Toro', 'Fantastique', 'Mexique', 'Réalisateur associé au Labyrinthe de Pan.', 'reverse', 'film', 'Quel film emblématique associer à Guillermo del Toro ?', 'Le Labyrinthe de Pan', null, null, null, null, 71059),
		('cinema_director_links', 'Alfonso Cuarón', 'Cinéma mexicain', 'Mexique', 'Réalisateur associé à Roma.', 'reverse', 'film', 'Quel film emblématique associer à Alfonso Cuarón ?', 'Roma', null, null, null, null, 71060),
		('cinema_director_links', 'Alejandro G. Iñárritu', 'Cinéma mexicain', 'Mexique', 'Réalisateur associé à Birdman.', 'reverse', 'film', 'Quel film emblématique associer à Alejandro G. Iñárritu ?', 'Birdman', null, null, null, null, 71061),
		('cinema_director_links', 'Pedro Almodóvar', 'Cinéma espagnol', 'Espagne', 'Réalisateur associé à Tout sur ma mère.', 'reverse', 'film', 'Quel film emblématique associer à Pedro Almodóvar ?', 'Tout sur ma mère', null, null, null, null, 71062),
		('cinema_director_links', 'Fernando Meirelles', 'Cinéma brésilien', 'Brésil', 'Réalisateur associé à Cidade de Deus.', 'reverse', 'film', 'Quel film emblématique associer à Fernando Meirelles ?', 'Cidade de Deus', null, null, null, null, 71063),
		('cinema_director_links', 'Lucrecia Martel', 'Cinéma argentin', 'Argentine', 'Réalisatrice associée à La Ciénaga.', 'reverse', 'film', 'Quel film emblématique associer à Lucrecia Martel ?', 'La Ciénaga', null, null, null, null, 71064),
		('cinema_director_links', 'Ken Loach', 'Cinéma britannique', 'Royaume-Uni', 'Réalisateur associé à Kes.', 'reverse', 'film', 'Quel film emblématique associer à Ken Loach ?', 'Kes', null, null, null, null, 71065),
		('cinema_director_links', 'Mike Leigh', 'Cinéma britannique', 'Royaume-Uni', 'Réalisateur associé à Secrets et Mensonges.', 'reverse', 'film', 'Quel film emblématique associer à Mike Leigh ?', 'Secrets et Mensonges', null, null, null, null, 71066),
		('cinema_director_links', 'Christopher Nolan', 'Cinéma contemporain', 'Royaume-Uni et États-Unis', 'Réalisateur associé à The Dark Knight.', 'reverse', 'film', 'Quel film emblématique associer à Christopher Nolan ?', 'The Dark Knight', null, null, null, null, 71067),
		('cinema_director_links', 'Quentin Tarantino', 'Cinéma contemporain', 'États-Unis', 'Réalisateur associé à Pulp Fiction.', 'reverse', 'film', 'Quel film emblématique associer à Quentin Tarantino ?', 'Pulp Fiction', null, null, null, null, 71068),
		('cinema_director_links', 'Peter Jackson', 'Fantasy', 'Nouvelle-Zélande', 'Réalisateur associé au Seigneur des anneaux.', 'reverse', 'film', 'Quel film emblématique associer à Peter Jackson ?', 'Le Seigneur des anneaux', null, null, null, null, 71069),
		('cinema_director_links', 'James Cameron', 'Science-fiction et spectacle', 'Canada', 'Réalisateur associé à Titanic.', 'reverse', 'film', 'Quel film emblématique associer à James Cameron ?', 'Titanic', null, null, null, null, 71070),
		('cinema_director_links', 'Greta Gerwig', 'Cinéma contemporain', 'États-Unis', 'Réalisatrice associée à Lady Bird.', 'reverse', 'film', 'Quel film emblématique associer à Greta Gerwig ?', 'Lady Bird', null, null, null, null, 71071),
		('cinema_director_links', 'Jordan Peele', 'Cinéma contemporain', 'États-Unis', 'Réalisateur associé à Get Out.', 'reverse', 'film', 'Quel film emblématique associer à Jordan Peele ?', 'Get Out', null, null, null, null, 71072),
		('cinema_director_links', 'Ryan Coogler', 'Cinéma contemporain', 'États-Unis', 'Réalisateur associé à Black Panther.', 'reverse', 'film', 'Quel film emblématique associer à Ryan Coogler ?', 'Black Panther', null, null, null, null, 71073),
		('cinema_director_links', 'Mati Diop', 'Cinéma contemporain', 'France et Sénégal', 'Réalisatrice associée à Atlantique.', 'reverse', 'film', 'Quel film emblématique associer à Mati Diop ?', 'Atlantique', null, null, null, null, 71074),
		('cinema_markers', 'Cinéma muet', 'Avant la généralisation du parlant', 'Technique et période', 'Période ou les films ne synchronisent pas encore les dialogues enregistrés.', 'standard', 'general', 'Quel repère du cinéma correspond aux films sans dialogues synchronisés ?', 'Cinéma muet', 'forward', 'general', 'Quelle période ou notion associer au Cinéma muet ?', 'Avant la généralisation du parlant', 72000),
		('cinema_markers', 'Cinématographe Lumière', '1895', 'France', 'Appareil associé aux premières projections publiques des frères Lumière.', 'standard', 'general', 'Quel appareil est associé aux premières projections publiques des frères Lumière ?', 'Cinématographe Lumière', 'forward', 'general', 'Quelle période ou notion associer au Cinématographe Lumière ?', '1895', 72001),
		('cinema_markers', 'Montage soviétique', 'Années 1920', 'URSS', 'Courant qui fait du montage un outil central du sens cinématographique.', 'standard', 'general', 'Quel courant fait du montage un outil central du sens cinématographique ?', 'Montage soviétique', 'forward', 'general', 'Quelle période ou notion associer au Montage soviétique ?', 'Années 1920', 72002),
		('cinema_markers', 'Expressionnisme allemand', 'Années 1920', 'Allemagne', 'Courant visuel associé aux décors stylisés, aux ombres et aux formes déformées.', 'standard', 'general', 'Quel courant associer aux décors stylisés, aux ombres et aux formes déformées ?', 'Expressionnisme allemand', 'forward', 'general', 'Quelle période ou notion associer à l’Expressionnisme allemand ?', 'Années 1920', 72003),
		('cinema_markers', 'Surréalisme au cinéma', 'Années 1920', 'Europe', 'Courant associé aux images de rêve, aux associations libres et à Un chien andalou.', 'standard', 'general', 'Quel courant associer aux images de rêve et à Un chien andalou ?', 'Surréalisme au cinéma', 'forward', 'general', 'Quelle période ou notion associer au Surréalisme au cinéma ?', 'Années 1920', 72004),
		('cinema_markers', 'Film noir', 'Années 1940-1950', 'États-Unis', 'Genre associé aux enquêtes criminelles, aux ombres et au pessimisme urbain.', 'standard', 'general', 'Quel genre associer aux enquêtes criminelles, aux ombres et au pessimisme urbain ?', 'Film noir', 'forward', 'general', 'Quelle période ou notion associer au Film noir ?', 'Années 1940-1950', 72005),
		('cinema_markers', 'Néoréalisme italien', 'Années 1940-1950', 'Italie', 'Courant italien associé aux tournages en extérieur et aux récits sociaux.', 'standard', 'general', 'Quel courant italien associer aux tournages en extérieur et aux récits sociaux ?', 'Néoréalisme italien', 'forward', 'general', 'Quelle période ou notion associer au Néoréalisme italien ?', 'Années 1940-1950', 72006),
		('cinema_markers', 'Nouvelle Vague', 'Années 1950-1960', 'France', 'Mouvement français associé à une mise en scène plus libre et au tournage léger.', 'standard', 'general', 'Quel mouvement français associer à une mise en scène plus libre et au tournage léger ?', 'Nouvelle Vague', 'forward', 'general', 'Quelle période ou notion associer à la Nouvelle Vague ?', 'Années 1950-1960', 72007),
		('cinema_markers', 'Free Cinema', 'Années 1950-1960', 'Royaume-Uni', 'Mouvement britannique associé à un regard social et documentaire.', 'standard', 'general', 'Quel mouvement britannique associer à un regard social et documentaire ?', 'Free Cinema', 'forward', 'general', 'Quelle période ou notion associer au Free Cinema ?', 'Années 1950-1960', 72008),
		('cinema_markers', 'Nouvel Hollywood', 'Années 1960-1970', 'États-Unis', 'Période américaine ou une génération de cinéastes renouvelle le cinéma de studio.', 'standard', 'general', 'Quelle période américaine voit une génération de cinéastes renouveler le cinéma de studio ?', 'Nouvel Hollywood', 'forward', 'general', 'Quelle période ou notion associer au Nouvel Hollywood ?', 'Années 1960-1970', 72009),
		('cinema_markers', 'Western', 'Genre classique', 'États-Unis', 'Genre associé à l’Ouest américain, aux frontières et aux figures de cow-boys.', 'standard', 'general', 'Quel genre associer à l’Ouest américain et aux figures de cow-boys ?', 'Western', 'forward', 'general', 'Quelle période ou notion associer au Western ?', 'Genre classique', 72010),
		('cinema_markers', 'Comédie musicale hollywoodienne', 'Âge d’or hollywoodien', 'États-Unis', 'Genre associé aux numéros chantés et dansés dans le cinéma de studio.', 'standard', 'general', 'Quel genre associer aux numéros chantés et dansés du cinéma de studio ?', 'Comédie musicale hollywoodienne', 'forward', 'general', 'Quelle période ou notion associer à la Comédie musicale hollywoodienne ?', 'Âge d’or hollywoodien', 72011),
		('cinema_markers', 'Science-fiction au cinéma', 'Genre transversal', 'International', 'Genre associé aux futurs possibles, aux technologies et aux mondes imaginaires.', 'standard', 'general', 'Quel genre associer aux futurs possibles, aux technologies et aux mondes imaginaires ?', 'Science-fiction au cinéma', 'forward', 'general', 'Quelle période ou notion associer à la Science-fiction au cinéma ?', 'Genre transversal', 72012),
		('cinema_markers', 'Film d’animation', 'Technique et genre', 'International', 'Forme de cinéma créée image par image ou par ordinateur.', 'standard', 'general', 'Quelle forme de cinéma est créée image par image ou par ordinateur ?', 'Film d’animation', 'forward', 'general', 'Quelle période ou notion associer au Film d’animation ?', 'Technique et genre', 72013),
		('cinema_markers', 'Stop motion', 'Technique d’animation', 'International', 'Technique d’animation qui photographie des objets image par image.', 'standard', 'general', 'Quelle technique anime des objets photographies image par image ?', 'Stop motion', 'forward', 'general', 'Quelle période ou notion associer au Stop motion ?', 'Technique d’animation', 72014),
		('cinema_markers', 'Technicolor', 'Couleur au cinéma', 'États-Unis', 'Procédé de couleur associé à plusieurs films de l’âge d’or hollywoodien.', 'standard', 'general', 'Quel procédé de couleur est associé à plusieurs films de l’âge d’or hollywoodien ?', 'Technicolor', 'forward', 'general', 'Quelle période ou notion associer au Technicolor ?', 'Couleur au cinéma', 72015),
		('cinema_markers', 'CinemaScope', 'Format large', 'États-Unis', 'Format large popularisé dans les années 1950 pour élargir l’image projetée.', 'standard', 'general', 'Quel format large est popularisé dans les années 1950 pour élargir l’image projetée ?', 'CinemaScope', 'forward', 'general', 'Quelle période ou notion associer au CinemaScope ?', 'Format large', 72016),
		('cinema_markers', 'Effets spéciaux numériques', 'Cinéma contemporain', 'International', 'Techniques informatiques utilisées pour créer ou transformer des images.', 'standard', 'general', 'Quelles techniques informatiques créent ou transforment des images au cinéma ?', 'Effets spéciaux numériques', 'forward', 'general', 'Quelle période ou notion associer aux Effets spéciaux numériques ?', 'Cinéma contemporain', 72017),
		('cinema_markers', 'Motion capture', 'Technique numérique', 'International', 'Technique qui enregistre les mouvements d’acteurs pour animer des personnages.', 'standard', 'general', 'Quelle technique enregistre les mouvements d’acteurs pour animer des personnages ?', 'Motion capture', 'forward', 'general', 'Quelle période ou notion associer à la Motion capture ?', 'Technique numérique', 72018),
		('cinema_markers', 'IMAX', 'Format de projection', 'International', 'Format associé à une image de très grande taille et à une projection immersive.', 'standard', 'general', 'Quel format de projection associer à une image très grande et immersive ?', 'IMAX', 'forward', 'general', 'Quelle période ou notion associer à l’IMAX ?', 'Format de projection', 72019),
		('cinema_markers', 'Palme d’or', 'Depuis 1955', 'Festival de Cannes', 'Récompense principale du Festival de Cannes.', 'standard', 'general', 'Quelle récompense est la distinction principale du Festival de Cannes ?', 'Palme d’or', 'forward', 'general', 'Quelle période ou notion associer à la Palme d’or ?', 'Depuis 1955', 72020),
		('cinema_markers', 'Oscars', 'Depuis 1929', 'États-Unis', 'Prix décernés par l’Academy of Motion Picture Arts and Sciences.', 'standard', 'general', 'Quels prix sont décernés par l’Academy of Motion Picture Arts and Sciences ?', 'Oscars', 'forward', 'general', 'Quelle période ou notion associer aux Oscars ?', 'Depuis 1929', 72021),
		('cinema_markers', 'Césars', 'Depuis 1976', 'France', 'Prix décernés chaque année au cinéma français.', 'standard', 'general', 'Quels prix récompensent chaque année le cinéma français ?', 'Césars', 'forward', 'general', 'Quelle période ou notion associer aux Césars ?', 'Depuis 1976', 72022),
		('cinema_markers', 'Festival de Cannes', 'Depuis 1946', 'France', 'Festival international de cinéma organisé sur la Côte d’Azur.', 'standard', 'general', 'Quel festival international de cinéma est organisé sur la Côte d’Azur ?', 'Festival de Cannes', 'forward', 'general', 'Quelle période ou notion associer au Festival de Cannes ?', 'Depuis 1946', 72023),
		('cinema_markers', 'Mostra de Venise', 'Depuis 1932', 'Italie', 'Festival de cinéma organisé à Venise.', 'standard', 'general', 'Quel festival de cinéma est organisé à Venise ?', 'Mostra de Venise', 'forward', 'general', 'Quelle période ou notion associer à la Mostra de Venise ?', 'Depuis 1932', 72024),
		('cinema_markers', 'Berlinale', 'Depuis 1951', 'Allemagne', 'Festival international de cinéma organisé à Berlin.', 'standard', 'general', 'Quel festival international de cinéma est organisé à Berlin ?', 'Berlinale', 'forward', 'general', 'Quelle période ou notion associer à la Berlinale ?', 'Depuis 1951', 72025),
		('cinema_markers', 'Studio Ghibli', 'Depuis 1985', 'Japon', 'Studio d’animation japonais associé à Hayao Miyazaki et Isao Takahata.', 'standard', 'general', 'Quel studio d’animation japonais est associé à Hayao Miyazaki et Isao Takahata ?', 'Studio Ghibli', 'forward', 'general', 'Quelle période ou notion associer au Studio Ghibli ?', 'Depuis 1985', 72026),
		('cinema_markers', 'Pixar', 'Depuis 1986', 'États-Unis', 'Studio d’animation associé à Toy Story et au cinéma en images de synthèse.', 'standard', 'general', 'Quel studio d’animation est associé à Toy Story et aux images de synthèse ?', 'Pixar', 'forward', 'general', 'Quelle période ou notion associer à Pixar ?', 'Depuis 1986', 72027),
		('cinema_markers', 'Disney Animation', 'Animation de studio', 'États-Unis', 'Studio associé à Blanche-Neige et les Sept Nains et à l’animation familiale.', 'standard', 'general', 'Quel studio associer à Blanche-Neige et les Sept Nains ?', 'Disney Animation', 'forward', 'general', 'Quelle période ou notion associer à Disney Animation ?', 'Animation de studio', 72028),
		('cinema_markers', 'Toho', 'Cinéma japonais', 'Japon', 'Studio japonais associé à Godzilla et à de nombreux films de genre.', 'standard', 'general', 'Quel studio japonais est associé à Godzilla ?', 'Toho', 'forward', 'general', 'Quelle période ou notion associer à Toho ?', 'Cinéma japonais', 72029),
		('cinema_markers', 'Bollywood', 'Industrie populaire', 'Inde', 'Nom courant donné à l’industrie du cinéma hindi de Mumbai.', 'standard', 'general', 'Quel nom courant désigne l’industrie du cinéma hindi de Mumbai ?', 'Bollywood', 'forward', 'general', 'Quelle période ou notion associer à Bollywood ?', 'Industrie populaire', 72030),
		('cinema_markers', 'Nollywood', 'Industrie contemporaine', 'Nigeria', 'Nom courant donné à l’industrie cinématographique nigériane.', 'standard', 'general', 'Quel nom courant désigne l’industrie cinématographique nigériane ?', 'Nollywood', 'forward', 'general', 'Quelle période ou notion associer à Nollywood ?', 'Industrie contemporaine', 72031),
		('cinema_markers', 'Cinéma d’auteur', 'Notion critique', 'International', 'Notion qui met en avant la signature personnelle du cineaste.', 'standard', 'general', 'Quelle notion met en avant la signature personnelle du cineaste ?', 'Cinéma d’auteur', 'forward', 'general', 'Quelle période ou notion associer au Cinéma d’auteur ?', 'Notion critique', 72032),
		('cinema_markers', 'Blockbuster', 'Cinéma populaire contemporain', 'États-Unis', 'Film à grand budget pensé pour une large exploitation commerciale.', 'standard', 'general', 'Quel terme désigne un film à grand budget pensé pour une large exploitation commerciale ?', 'Blockbuster', 'forward', 'general', 'Quelle période ou notion associer au Blockbuster ?', 'Cinéma populaire contemporain', 72033),
		('cinema_markers', 'Saga Star Wars', 'Depuis 1977', 'États-Unis', 'Saga de science-fiction lancée par George Lucas.', 'standard', 'general', 'Quelle saga de science-fiction à ete lancée par George Lucas ?', 'Saga Star Wars', 'forward', 'general', 'Quelle période ou notion associer à la Saga Star Wars ?', 'Depuis 1977', 72034),
		('cinema_markers', 'Saga James Bond', 'Depuis 1962', 'Royaume-Uni', 'Serie de films d’espionnage centrée sur l’agent 007.', 'standard', 'general', 'Quelle saga d’espionnage est centrée sur l’agent 007 ?', 'Saga James Bond', 'forward', 'general', 'Quelle période ou notion associer à la Saga James Bond ?', 'Depuis 1962', 72035),
		('cinema_markers', 'Univers Marvel au cinéma', 'Depuis 2008', 'États-Unis', 'Ensemble de films de super-héros interconnectés.', 'standard', 'general', 'Quel univers cinématographique regroupe des films de super-héros interconnectés depuis 2008 ?', 'Univers Marvel au cinéma', 'forward', 'general', 'Quelle période ou notion associer à l’Univers Marvel au cinéma ?', 'Depuis 2008', 72036),
		('cinema_markers', 'Kaiju', 'Cinéma de monstres', 'Japon', 'Terme japonais associé aux films de monstres géants comme Godzilla.', 'standard', 'general', 'Quel terme japonais désigne les films de monstres géants comme Godzilla ?', 'Kaiju', 'forward', 'general', 'Quelle période ou notion associer au Kaiju ?', 'Cinéma de monstres', 72037),
		('cinema_markers', 'Chanbara', 'Cinéma de sabre', 'Japon', 'Genre japonais associé aux films de sabre et aux samouraïs.', 'standard', 'general', 'Quel genre japonais associer aux films de sabre et aux samouraïs ?', 'Chanbara', 'forward', 'general', 'Quelle période ou notion associer au Chanbara ?', 'Cinéma de sabre', 72038),
		('cinema_markers', 'Wuxia', 'Cinéma d’arts martiaux', 'Chine', 'Genre chinois associé aux héros errants, aux arts martiaux et à l’aventure.', 'standard', 'general', 'Quel genre chinois associer aux héros errants, aux arts martiaux et à l’aventure ?', 'Wuxia', 'forward', 'general', 'Quelle période ou notion associer au Wuxia ?', 'Cinéma d’arts martiaux', 72039),
		('cinema_markers', 'Comédie italienne', 'Années 1950-1970', 'Italie', 'Genre italien mêlant satire sociale et situations comiques.', 'standard', 'general', 'Quel genre italien mêle satire sociale et situations comiques ?', 'Comédie italienne', 'forward', 'general', 'Quelle période ou notion associer à la Comédie italienne ?', 'Années 1950-1970', 72040),
		('cinema_markers', 'Giallo', 'Thriller italien', 'Italie', 'Genre italien associant enquete, suspense et style visuel marqué.', 'standard', 'general', 'Quel genre italien associé enquete, suspense et style visuel marqué ?', 'Giallo', 'forward', 'general', 'Quelle période ou notion associer au Giallo ?', 'Thriller italien', 72041),
		('cinema_markers', 'Dogme 95', 'Années 1990', 'Danemark', 'Mouvement danois fondé sur des règles de tournage volontairement strictes.', 'standard', 'general', 'Quel mouvement danois impose des règles de tournage volontairement strictes ?', 'Dogme 95', 'forward', 'general', 'Quelle période ou notion associer à Dogme 95 ?', 'Années 1990', 72042),
		('cinema_markers', 'Cinéma vérité', 'Documentaire', 'France', 'Approche documentaire cherchant à capter le réel avec une forte présence de la caméra.', 'standard', 'general', 'Quelle approche documentaire cherche à capter le réel avec une forte présence de la caméra ?', 'Cinéma vérité', 'forward', 'general', 'Quelle période ou notion associer au Cinéma vérité ?', 'Documentaire', 72043),
		('cinema_markers', 'Cinéma direct', 'Documentaire', 'Amérique du Nord et Europe', 'Approche documentaire associée à des équipes légères et au son synchrone.', 'standard', 'general', 'Quelle approche documentaire est associée à des équipes légères et au son synchrone ?', 'Cinéma direct', 'forward', 'general', 'Quelle période ou notion associer au Cinéma direct ?', 'Documentaire', 72044),
		('cinema_markers', 'Found footage', 'Dispositif narratif', 'International', 'Dispositif qui présente le film comme des images retrouvées.', 'standard', 'general', 'Quel dispositif présente le film comme des images retrouvées ?', 'Found footage', 'forward', 'general', 'Quelle période ou notion associer au Found footage ?', 'Dispositif narratif', 72045),
		('cinema_markers', 'Plan-séquence', 'Technique de mise en scène', 'International', 'Plan long qui donné l’impression d’une action continue sans coupe visible.', 'standard', 'general', 'Quelle technique désigne un plan long sans coupe visible ?', 'Plan-séquence', 'forward', 'general', 'Quelle période ou notion associer au Plan-séquence ?', 'Technique de mise en scène', 72046),
		('cinema_markers', 'Jump cut', 'Technique de montage', 'International', 'Coupe visible qui crée une rupture dans la continuité du mouvement ou du temps.', 'standard', 'general', 'Quelle technique de montage crée une rupture visible dans la continuité ?', 'Jump cut', 'forward', 'general', 'Quelle période ou notion associer au Jump cut ?', 'Technique de montage', 72047),
		('cinema_markers', 'Champ-contrechamp', 'Technique de découpage', 'International', 'Alternance de plans utilisée notamment pour filmer un dialogue.', 'standard', 'general', 'Quelle alternance de plans est souvent utilisée pour filmer un dialogue ?', 'Champ-contrechamp', 'forward', 'general', 'Quelle période ou notion associer au Champ-contrechamp ?', 'Technique de découpage', 72048),
		('cinema_markers', 'Storyboard', 'Préparation du film', 'International', 'Suite de dessins qui prépare le découpage visuel d’une scène.', 'standard', 'general', 'Quel outil prépare le découpage visuel d’une scène sous forme de dessins ?', 'Storyboard', 'forward', 'general', 'Quelle période ou notion associer au Storyboard ?', 'Préparation du film', 72049),
		('cinema_markers', 'Producteur', 'Métier du cinéma', 'International', 'Personne ou structure qui porte le financement et l’organisation d’un film.', 'standard', 'general', 'Quel métier porte le financement et l’organisation d’un film ?', 'Producteur', 'forward', 'general', 'Quelle période ou notion associer au Producteur ?', 'Métier du cinéma', 72050),
		('cinema_markers', 'Directeur de la photographie', 'Métier du cinéma', 'International', 'Responsable de l’image, de la lumière et du cadre avec le réalisateur.', 'standard', 'general', 'Quel métier est responsable de l’image, de la lumière et du cadre ?', 'Directeur de la photographie', 'forward', 'general', 'Quelle période ou notion associer au Directeur de la photographie ?', 'Métier du cinéma', 72051),
		('cinema_markers', 'Monteur', 'Métier du cinéma', 'International', 'Personne qui assemble les plans et construit le rythme du film.', 'standard', 'general', 'Quel métier assemble les plans et construit le rythme du film ?', 'Monteur', 'forward', 'general', 'Quelle période ou notion associer au Monteur ?', 'Métier du cinéma', 72052),
		('cinema_markers', 'Compositeur de musique de film', 'Métier du cinéma', 'International', 'Createur de la musique originale d’un film.', 'standard', 'general', 'Quel métier crée la musique originale d’un film ?', 'Compositeur de musique de film', 'forward', 'general', 'Quelle période ou notion associer au Compositeur de musique de film ?', 'Métier du cinéma', 72053),
		('cinema_markers', 'Doublage', 'Technique sonore', 'International', 'Remplacement des voix originales par des voix enregistrees dans une autre langue.', 'standard', 'general', 'Quelle technique remplace les voix originales par des voix dans une autre langue ?', 'Doublage', 'forward', 'general', 'Quelle période ou notion associer au Doublage ?', 'Technique sonore', 72054),
		('cinema_markers', 'Sous-titrage', 'Technique de traduction', 'International', 'Affichage de textes traduisant les dialogues ou les informations sonores.', 'standard', 'general', 'Quelle technique affiche un texte traduisant les dialogues ou informations sonores ?', 'Sous-titrage', 'forward', 'general', 'Quelle période ou notion associer au Sous-titrage ?', 'Technique de traduction', 72055),
		('cinema_markers', 'Oscar du film international', 'Catégorie de récompense', 'États-Unis', 'Catégorie des Oscars consacrée aux films produits hors des États-Unis.', 'standard', 'general', 'Quelle categorie des Oscars récompense des films produits hors des États-Unis ?', 'Oscar du film international', 'forward', 'general', 'Quelle période ou notion associer à l’Oscar du film international ?', 'Catégorie de récompense', 72056),
		('cinema_markers', 'Lion d’or', 'Récompense de festival', 'Mostra de Venise', 'Récompense principale de la Mostra de Venise.', 'standard', 'general', 'Quelle récompense est la distinction principale de la Mostra de Venise ?', 'Lion d’or', 'forward', 'general', 'Quelle période ou notion associer au Lion d’or ?', 'Récompense de festival', 72057),
		('cinema_markers', 'Ours d’or', 'Récompense de festival', 'Berlinale', 'Récompense principale de la Berlinale.', 'standard', 'general', 'Quelle récompense est la distinction principale de la Berlinale ?', 'Ours d’or', 'forward', 'general', 'Quelle période ou notion associer à l’Ours d’or ?', 'Récompense de festival', 72058),
		('cinema_markers', 'Cinéma de Hong Kong', 'Années 1970-1990', 'Hong Kong', 'Cinéma associé notamment aux films d’action, d’arts martiaux et de polar.', 'standard', 'general', 'Quel cinéma est associé aux films d’action, d’arts martiaux et de polar de Hong Kong ?', 'Cinéma de Hong Kong', 'forward', 'general', 'Quelle période ou notion associer au Cinéma de Hong Kong ?', 'Années 1970-1990', 72059),
		('cinema_markers', 'Animation japonaise', 'Cinéma d’animation', 'Japon', 'Tradition d’animation associée aux studios japonais et aux anime.', 'standard', 'general', 'Quelle tradition d’animation associer aux studios japonais et aux anime ?', 'Animation japonaise', 'forward', 'general', 'Quelle période ou notion associer à l’Animation japonaise ?', 'Cinéma d’animation', 72060),
		('cinema_markers', 'Film de samourai', 'Genre japonais', 'Japon', 'Genre japonais centre sur les guerriers samouraïs et les codes du sabre.', 'standard', 'general', 'Quel genre japonais est centre sur les guerriers samouraïs et les codes du sabre ?', 'Film de samourai', 'forward', 'general', 'Quelle période ou notion associer au Film de samourai ?', 'Genre japonais', 72061),
		('cinema_markers', 'Road movie', 'Genre narratif', 'États-Unis et international', 'Genre construit autour d’un voyage et d’un deplacement sur la route.', 'standard', 'general', 'Quel genre est construit autour d’un voyage sur la route ?', 'Road movie', 'forward', 'general', 'Quelle période ou notion associer au Road movie ?', 'Genre narratif', 72062),
		('cinema_markers', 'Slapstick', 'Comédie burlesque', 'États-Unis', 'Forme de comédie fondée sur le gag visuel et l’action physique.', 'standard', 'general', 'Quelle forme de comédie repose sur le gag visuel et l’action physique ?', 'Slapstick', 'forward', 'general', 'Quelle période ou notion associer au Slapstick ?', 'Comédie burlesque', 72063),
		('cinema_markers', 'Screwball comedy', 'Comédie hollywoodienne', 'États-Unis', 'Comédie américaine vive, souvent fondée sur les dialogues et les quiproquos.', 'standard', 'general', 'Quelle comédie hollywoodienne est vive et souvent fondée sur les dialogues et les quiproquos ?', 'Screwball comedy', 'forward', 'general', 'Quelle période ou notion associer à la Screwball comedy ?', 'Comédie hollywoodienne', 72064),
		('cinema_markers', 'Thriller psychologique', 'Genre narratif', 'International', 'Genre centre sur la tension mentale, le doute et la perception des personnages.', 'standard', 'general', 'Quel genre centre son suspense sur la tension mentale et la perception des personnages ?', 'Thriller psychologique', 'forward', 'general', 'Quelle période ou notion associer au Thriller psychologique ?', 'Genre narratif', 72065),
		('cinema_markers', 'Film de cape et d’épée', 'Genre d’aventure', 'Europe', 'Genre associé aux duels, aux héros d’aventure et aux récits historiques.', 'standard', 'general', 'Quel genre associer aux duels, aux héros d’aventure et aux récits historiques ?', 'Film de cape et d’épée', 'forward', 'general', 'Quelle période ou notion associer au Film de cape et d’épée ?', 'Genre d’aventure', 72066),
		('cinema_markers', 'Nouvelle Vague taïwanaise', 'Années 1980-1990', 'Taiwan', 'Mouvement associé à Edward Yang, Hou Hsiao-hsien et au renouvellement du cinéma taïwanais.', 'standard', 'general', 'Quel mouvement associer à Edward Yang, Hou Hsiao-hsien et au cinéma taïwanais des années 1980 ?', 'Nouvelle Vague taïwanaise', 'forward', 'general', 'Quelle période ou notion associer à la Nouvelle Vague taïwanaise ?', 'Années 1980-1990', 72067),
		('cinema_markers', 'Cinéma iranien contemporain', 'Depuis les années 1980', 'Iran', 'Cinéma associé à des récits sobres, sociaux et souvent réflexifs.', 'standard', 'general', 'Quel cinéma contemporain associer à des récits sobres, sociaux et réflexifs ?', 'Cinéma iranien contemporain', 'forward', 'general', 'Quelle période ou notion associer au Cinéma iranien contemporain ?', 'Depuis les années 1980', 72068),
		('cinema_markers', 'Réalisme poétique français', 'Années 1930', 'France', 'Courant français associé aux décors populaires, au fatalisme et à une atmosphère mélancolique.', 'standard', 'general', 'Quel courant français associer aux décors populaires, au fatalisme et à une atmosphère mélancolique ?', 'Réalisme poétique français', 'forward', 'general', 'Quelle période ou notion associer au Réalisme poétique français ?', 'Années 1930', 72069),
		('cinema_markers', 'Comédies Ealing', 'Années 1940-1950', 'Royaume-Uni', 'Comédies britanniques associées aux studios Ealing.', 'standard', 'general', 'Quelles comédies britanniques sont associées aux studios Ealing ?', 'Comédies Ealing', 'forward', 'general', 'Quelle période ou notion associer aux Comédies Ealing ?', 'Années 1940-1950', 72070),
		('cinema_markers', 'Cinéma de genre coréen', 'Cinéma contemporain', 'Corée du Sud', 'Cinéma associé aux thrillers, drames et films de genre sud-coréens.', 'standard', 'general', 'Quel cinéma contemporain associer aux thrillers et films de genre sud-coréens ?', 'Cinéma de genre coréen', 'forward', 'general', 'Quelle période ou notion associer au Cinéma de genre coréen ?', 'Cinéma contemporain', 72071),
		('cinema_markers', 'Comédie romantique', 'Genre populaire', 'International', 'Genre centre sur une relation amoureuse et des obstacles comiques ou sentimentaux.', 'standard', 'general', 'Quel genre centre son récit sur une relation amoureuse et des obstacles comiques ou sentimentaux ?', 'Comédie romantique', 'forward', 'general', 'Quelle période ou notion associer à la Comédie romantique ?', 'Genre populaire', 72072),
		('cinema_markers', 'Documentaire', 'Forme cinématographique', 'International', 'Forme qui travaille à partir de personnes, de faits ou de situations réelles.', 'standard', 'general', 'Quelle forme cinématographique travaille à partir de personnes, de faits ou de situations réelles ?', 'Documentaire', 'forward', 'general', 'Quelle période ou notion associer au Documentaire ?', 'Forme cinématographique', 72073),
		('cinema_markers', 'Court métrage', 'Format court', 'International', 'Film de durée courte, souvent utilisé pour l’expérimentation ou les débuts de cinéastes.', 'standard', 'general', 'Quel format désigne un film de durée courte ?', 'Court métrage', 'forward', 'general', 'Quelle période ou notion associer au Court métrage ?', 'Format court', 72074)
	) as values_table(collection, title, period_label, location_label, short_summary, primary_direction, primary_type, primary_question, primary_answer, secondary_direction, secondary_type, secondary_question, secondary_answer, sort_order)
), inserted_items as (
	insert into public.culture_items (
		category,
		item_type,
		collection,
		title,
		period_label,
		location_label,
		short_summary,
		sort_order
	)
	select
		'cinema',
		case
			when source_items.collection = 'cinema_markers' then 'cultural_marker'
			else 'knowledge_card'
		end,
		source_items.collection,
		source_items.title,
		source_items.period_label,
		source_items.location_label,
		source_items.short_summary,
		source_items.sort_order
	from source_items
	where not exists (
		select 1
		from public.culture_items existing_items
		where existing_items.category = 'cinema'
			and existing_items.collection = source_items.collection
			and existing_items.title = source_items.title
	)
	returning id, collection, title
), source_prompts as (
	select
		source_items.collection,
		source_items.title as item_title,
		source_items.primary_direction as prompt_direction,
		source_items.primary_type as prompt_type,
		source_items.primary_question as question,
		source_items.primary_answer as answer,
		10 as sort_order
	from source_items
	where source_items.primary_question is not null

	union all

	select
		source_items.collection,
		source_items.title as item_title,
		source_items.secondary_direction as prompt_direction,
		source_items.secondary_type as prompt_type,
		source_items.secondary_question as question,
		source_items.secondary_answer as answer,
		20 as sort_order
	from source_items
	where source_items.secondary_question is not null
), all_cinema_items as (
	select inserted_items.id, inserted_items.collection, inserted_items.title
	from inserted_items

	union all

	select existing_items.id, existing_items.collection, existing_items.title
	from public.culture_items existing_items
	join source_items
		on source_items.collection = existing_items.collection
		and source_items.title = existing_items.title
	where existing_items.category = 'cinema'
)
insert into public.culture_prompts (
	item_id,
	prompt_direction,
	prompt_type,
	question,
	answer,
	answer_aliases,
	choices,
	sort_order
)
select
	all_cinema_items.id,
	source_prompts.prompt_direction,
	source_prompts.prompt_type,
	source_prompts.question,
	source_prompts.answer,
	array[]::text[],
	array[]::text[],
	source_prompts.sort_order
from source_prompts
join all_cinema_items
	on all_cinema_items.collection = source_prompts.collection
	and all_cinema_items.title = source_prompts.item_title
where not exists (
	select 1
	from public.culture_prompts existing_prompts
	where existing_prompts.item_id = all_cinema_items.id
		and existing_prompts.question = source_prompts.question
);

-- Requetes de controle utiles apres application réelle :
-- select collection, count(*) from public.culture_items where category = 'cinema' and collection in ('cinema_film_dates', 'cinema_director_links', 'cinema_markers') group by collection order by collection;
-- select culture_items.collection, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'cinema' and culture_items.collection in ('cinema_film_dates', 'cinema_director_links', 'cinema_markers') group by culture_items.collection order by culture_items.collection;
-- select culture_prompts.prompt_type, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'cinema' and culture_items.collection in ('cinema_film_dates', 'cinema_director_links', 'cinema_markers') group by culture_prompts.prompt_type order by culture_prompts.prompt_type;
-- select culture_prompts.question, count(*) from public.culture_prompts join public.culture_items on culture_items.id = culture_prompts.item_id where culture_items.category = 'cinema' and culture_items.collection in ('cinema_film_dates', 'cinema_director_links', 'cinema_markers') group by culture_prompts.question having count(*) > 1 order by count(*) desc, culture_prompts.question;
-- select collection, title, count(*) from public.culture_items where category = 'cinema' and collection in ('cinema_film_dates', 'cinema_director_links', 'cinema_markers') group by collection, title having count(*) > 1 order by collection, title;
